[Maps] Update map report image test threshold for new EMS styles (#167162)
Updated EMS Styles are waiting to be put into production. They are
already available in Elastic staging environment
([preview](maps-staging.elastic.co/?manifest=testing)). This PR is a
safe measure to ensure that this change do not break our CI tests.

The process has been as follows:

1. Momentarily replaces the EMS Tile Service `tileApiUrl` by our staging
server to force the use of the new styles and check which tests break
with the slightly different basemaps at
[12481c6](https://github.com/elastic/kibana/pull/167162/commits/12481c6ada986cda258f37108f5f0dd6c85f7689)
2. Look for related [broken
tests](https://buildkite.com/elastic/kibana-pull-request/builds/161870)
```
Error: expected 0.030813687704837327 to be below 0.03
```
4. Adjust the threshold for the dashboard report, since the new value
was slightly over the limit
[e655b84](https://github.com/elastic/kibana/pull/167162/commits/e655b845695788c67356de115ab6e4627a42b07b)
5. Wait for a green CI (this took a few days because of unrelated issues
with Kibana CI)
6. Revert the `tileApiUrl` change to its original value
[c0030bc](https://github.com/elastic/kibana/pull/167162/commits/c0030bcff1a1de14860a05c27f26af45fda5e240)

---------

Co-authored-by: Kibana Machine <42973632+kibanamachine@users.noreply.github.com>