Update saved objects migration integration test archive
This test archive is currently causing ES to shutdown with an error:

```
java.lang.IllegalStateException: cannot upgrade a node from version
[7.7.2] directly to version [8.0.2], upgrade to version [7.17.0]
first.
```

This change extracts the 7.7.2 archive into a 7.17 install and re-zips
it.