Fix odd TS error
Without hardcoding the path to the @types/react-syntax-highlighter
package, the `scripts/type_check` test would exit with a few of these
errors:

    error TS7016: Could not find a declaration file for module
    'react-syntax-highlighter/dist/cjs/prism-light'.
    '/dev/shm/workspace/kibana/node_modules/react-syntax-highlighter/dist/cjs/prism-light.js'
    implicitly has an 'any' type.

    Try `npm i --save-dev @types/react-syntax-highlighter` if it exists
    or add a new declaration (.d.ts) file containing `declare module
    'react-syntax-highlighter/dist/cjs/prism-light';`

However, there doesn't seem to be any difference in how
`react-syntax-highlighter` is used. So why this error suddenly popped up
is odd.