[security_page] improve force logout (#170227)
## Summary

Addressing `forceLogout` flakiness
https://buildkite.com/elastic/appex-qa-serverless-kibana-ftr-tests/builds/370

```
Error: timed out waiting for Waiting for logout to complete
    at onFailure (retry_for_truthy.ts:39:13)
    at retryForSuccess (retry_for_success.ts:59:13)
    at retryForTruthy (retry_for_truthy.ts:27:3)
    at RetryService.waitFor (retry.ts:59:5)
    at SecurityPageObject.forceLogout (security_page.ts:319:7)
    at Object.forceLogout (svl_common_page.ts:95:7)
    at Context. (view_case.ts:44:7)
    at Object.apply (wrap_function.js:73:16)
```

<img width="1294" alt="image"
src="https://github.com/elastic/kibana/assets/10977896/92ff13da-2c80-4eb7-8b3e-63779fb61075">

Flaky-test-runner:
https://buildkite.com/elastic/kibana-flaky-test-suite-runner/builds/3839
200/200

(cherry picked from commit f21e31acf26e18e76d32cfafb0cfae83f98bd7f5)