[Security Solution] Fix DW related failures in MKI pipeline (#222181)
**Follow-up to: https://github.com/elastic/kibana/pull/221615**

## Summary
This PR fixes the following error in MKI pipelines ([example
pipeline](https://buildkite.com/elastic/kibana-serverless-security-solution-quality-gate-defend-workflows/builds/2835#01972415-5489-4236-a3ee-6176a89600d1)).

```
CypressError: `cy.then()` failed because you are mixing up async and sync code.
```

## Fix
- MKI pipeline for Defend Workflows:
[passed](https://buildkite.com/elastic/kibana-serverless-security-solution-quality-gate-defend-workflows/builds/2848)

## Cause
A recent [PR](https://github.com/elastic/kibana/pull/221615/files) added
a cookie count assertion into the `login` function used by Defend
Workflows.

```js
cy.task('getSessionCookie', user)
  .then(
    // ...
  )
  .then(() => {
    cy.getCookies().then((cookies) => {
      const sessionCookies = cookies.filter((cookie) => cookie.name === 'sid');
      expect(sessionCookies).to.have.length(1);
    });

    return { username, password };
  });
```

It turned out Cypress doesn't allow having a sync return in a `then`
that also does async actions.