Use `ALWAYS_COMPATIBLE_VERSION` for `version` in `kibana.json`
Previous CI run complained about a missing version, so I set to `"0.0.2"` thinking I was versioning _the plugin_

A subsequent CI run failed with

```
Error: Failed to initialize plugins:
17:47:29 	Plugin "integrations_manager" is only compatible with Kibana version "0.0.2", but used Kibana version is "8.0.0". (incompatible-version, /var/lib/jenkins/workspace/elastic+kibana+pull-request/JOB/x-pack-intake/node/immutable/kibana/x-pack/plugins/integrations_manager/kibana.json)
```

Using the `ALWAYS_COMPATIBLE_VERSION` value from https://github.com/elastic/kibana/blob/84b595e49fa7e09b89edabdec5ba394f2d3237cb/src/core/server/plugins/discovery/plugin_manifest_parser.ts#L39 to get this to pass CI & revisit later