Use getUrlPartsWithStrippedDefaultPort instead of getUrlParts (#199264)
## Summary

Use getUrlPartsWithStrippedDefaultPort to avoid this
[issue](https://github.com/elastic/kibana/pull/195902#issuecomment-2411667499)
on MKI:

```
Serverless Observability - Deployment-agnostic api integration - Custom Threshold rule AVG - PCT - FIRED Rule creation should set correct action variables

Error: expected 'https://bk-serverless-ftr-3067-e697d43e3ad9-e0ac80.kb.eu-west-1.aws.qa.elastic.cloud/app/observability/alerts/1e0c2d3e-e5c2-4bfe-9df0-d46681253b9f'
to sort of equal 'https://bk-serverless-ftr-3067-e697d43e3ad9-e0ac80.kb.eu-west-1.aws.qa.elastic.cloud:443/app/observability/alerts/1e0c2d3e-e5c2-4bfe-9df0-d46681253b9f'
```

(cherry picked from commit 996104f2eae2a3eb2412d5bb4ca52e89a5dbb1db)