fix dysfunctional `read_jest_help.mjs` (#236143)
## Summary
`src/platform/packages/shared/kbn-test/src/jest/run.ts` makes a
reference to an existing script, `read_jest_help.mjs`. However this file
doesn't work as advertised.

```
node:internal/modules/esm/resolve:204
  const resolvedOption = FSLegacyMainResolve(pkgPath, packageConfig.main, baseStringified);
                         ^

Error: Cannot find package '/Users/alex/Git/elastic-kibana/node_modules/@kbn/dev-cli-errors/index.js' imported from /Users/alex/Git/elastic-kibana/scripts/read_jest_help.mjs
    at legacyMainResolve (node:internal/modules/esm/resolve:204:26)
    at packageResolve (node:internal/modules/esm/resolve:778:12)
```

An easy way to fix this was to move it to cjs, updating the imports, and
it started working again.
The update to the
`src/platform/packages/shared/kbn-test/src/jest/jest_flags.json` is
through running the script.