[ResponseOps] Fix screenshotting flaky test (#235061)
Fixes #156106

## Summary

Interesting problem here. When testing screenshots, we display the
memory and CPU used.

One of the tests used a regular expression (regex) to ensure the memory
value was rendered, but it always expected the number to include a
decimal point.

Sometimes the test would result in a round number, and the regex would
fail, hence the flakiness.

```
Error: expected 'Memory\n80 MB' to match /\d+\.\d+ MB/
```

I made the decimal point optional in the regex.

## Flaky test runner

https://buildkite.com/elastic/kibana-flaky-test-suite-runner/builds/9318