Add API key info to relevant authentication error messages
When an authentication error is logged, because of an invalidated
API key, no information is provided in the log message.  Even the
fact that it's an invalidated API key is not provided.

This PR adds the `additional_unsuccessful_credentials` property to
relevant error messages, which indicates the keys are invalid, and
also provides the API key id.

The API key id can be logged, but it should not be presented in a UX, so
should not written to the event log, alerts, etc.

The message logged today is:

    Executing Rule default:.<type>:<id> has resulted in Error: security_exception
    Root causes:
    security_exception: unable to authenticate with provided credentials
    and anonymous access is not allowed for this request

With this PR, the message will be as follows, basically, adding the final line,
everything else is the same:

    Executing Rule default:.<type>:<id> has resulted in Error: security_exception
    Root causes:
    security_exception: unable to authenticate with provided credentials
    and anonymous access is not allowed for this request,
    caused by: "API key: api key [uydIypsBsFtA59dS1JcM] has been invalidated"