[scout/security] improve alerting table wait (#216262)
## Summary

This PR improves waiting for Alerts table to be loaded.

Relying on the first alert might cause flakiness in the future test
cases, I changed the rule name to be unique for test run and search
alert based on its rule name, not the first row.

If the alert is missing or it has a wrong name, the test will fail with
clear message:

```
    Error: Alert with rule 'xys' is not displayed

    Timed out 10000ms waiting for expect(locator).toBeVisible()

    Locator: locator('div.euiDataGridRow').filter({ hasText: 'xys' })
    Expected: visible
    Received: <element(s) not found>
    Call log:
      - Alert with rule 'xys' is not displayed with timeout 10000ms
      - waiting for locator('div.euiDataGridRow').filter({ hasText: 'xys' })
```

---------

Co-authored-by: kibanamachine <42973632+kibanamachine@users.noreply.github.com>
(cherry picked from commit d1707cc872ce95a251e7ba2708e29102ccbc64bf)