[Fleet] Include hidden data streams in package upgrade (#158654)
## Summary

APM team reported an issue in 8.8 where some of their newer data streams
were not rolled over as expected.
It turned out these are hidden data streams and those were not updated
in Fleet when a new version of a package is installed.

To test:
- Start up a kibana
- Install apm 8.7.0 package
[apm-8.7.0.zip](https://github.com/elastic/kibana/files/11600335/apm-8.7.0.zip)
```
url -XPOST -H 'content-type: application/zip' -H 'kbn-xsrf: true' http://localhost:5601/julia/api/fleet/epm/packages -u elastic:changeme --data-binary @apm-8.7.0.zip
```
- Index a doc to apm datastream
```
POST metrics-apm.service_summary.10m-default/_doc
        {
          "@timestamp": "2023-05-30T07:50:00.000Z",
          "agent": {
            "name": "go"
          },
          "data_stream": {
            "dataset": "apm.service_summary.10m",
            "namespace": "default",
            "type": "metrics"
          },
          "ecs": {
            "version": "8.6.0-dev"
          },
          "event": {
            "agent_id_status": "missing",
            "ingested": "2023-05-30T07:57:12Z"
          },
          "metricset": {
            "interval": "10m",
            "name": "service_summary"
          },
          "observer": {
            "hostname": "047e282994fb",
            "type": "apm-server",
            "version": "8.7.0"
          },
          "processor": {
            "event": "metric",
            "name": "metric"
          },
             "service": {
            "language": {
              "name": "go"
            },
            "name": "___main_elastic_cloud_87_ilm_fix"
          }
        }
```
- Install apm 8.8.0 package
[apm-8.8.0.zip](https://github.com/elastic/kibana/files/11599946/apm-8.8.0.zip)
```
url -XPOST -H 'content-type: application/zip' -H 'kbn-xsrf: true' http://localhost:5601/julia/api/fleet/epm/packages -u elastic:changeme --data-binary @apm-8.8.0.zip
```
- Expect that the hidden datastream is updated and rolls over on
failures.

```
[2023-05-30T15:23:21.666+02:00][DEBUG][plugins.fleet] Updating mappings for metrics-apm.service_summary.10m-default
[2023-05-30T15:23:21.670+02:00][ERROR][plugins.fleet] Mappings update for metrics-apm.service_summary.10m-default failed
[2023-05-30T15:23:21.671+02:00][ERROR][plugins.fleet] ResponseError: illegal_argument_exception
        Root causes:
                illegal_argument_exception: Mapper for [processor.name] conflicts with existing mapper:
        Cannot update parameter [value] from [metric] to [null]
```

<img width="995" alt="image"
src="https://github.com/elastic/kibana/assets/90178898/6a5a1abc-30f2-4b2f-a949-5b727cc91f57">
<img width="1175" alt="image"
src="https://github.com/elastic/kibana/assets/90178898/8e18c40f-6b7f-4810-a9e4-9685a7fa5d0c">

Added integration test.

### Checklist

- [x] [Unit or functional
tests](https://www.elastic.co/guide/en/kibana/master/development-tests.html)
were updated or added to match the most common scenarios

(cherry picked from commit 58e0fdf096df0af53e5902ee9da9cc5c63d77847)