[8.19] [ska] create platform shared package for Cypress test helpers (#224361) (#225073)
# Backport

This will backport the following commits from `main` to `8.19`:
- [[ska] create platform shared package for Cypress test helpers
(#224361)](https://github.com/elastic/kibana/pull/224361)

<!--- Backport version: 10.0.1 -->

### Questions ?
Please refer to the [Backport tool
documentation](https://github.com/sorenlouv/backport)

<!--BACKPORT [{"author":{"name":"Dzmitry
Lemechko","email":"dzmitry.lemechko@elastic.co"},"sourceCommit":{"committedDate":"2025-06-24T08:51:12Z","message":"[ska]
create platform shared package for Cypress test helpers (#224361)\n\n##
Summary\n\nPart of
https://github.com/elastic/kibana-team/issues/1503\n\nThis PR adds
`kbn/cypress-test-helper` as platform shared package to\nreplace invalid
imports from private `security-solution` plugin in\nplatform shared
plugin `osquery`.\n\nThe reason is that we are **currently blocked with
x-pack relocation due\nto circular dependency**, e.g.
in\nhttps://github.com/elastic/kibana/pull/223897\n\n```\n\ninfo
starting [tsc] > node_modules/typescript/bin/tsc -b tsconfig.refs.json
--pretty\n--\n  | 2025-06-13 13:17:30 UTC | proc [tsc] error TS6202:
Project references may not form a circular graph. Cycle detected:
/opt/buildkite-agent/builds/bk-agent-prod-gcp-1749820368903967112/elastic/kibana-pull-request/kibana/tsconfig.refs.json\n 
| 2025-06-13 13:17:30 UTC | proc [tsc]
/opt/buildkite-agent/builds/bk-agent-prod-gcp-1749820368903967112/elastic/kibana-pull-request/kibana/x-pack/platform/plugins/shared/osquery/cypress/tsconfig.type_check.json\n 
| 2025-06-13 13:17:30 UTC | proc [tsc]
/opt/buildkite-agent/builds/bk-agent-prod-gcp-1749820368903967112/elastic/kibana-pull-request/kibana/x-pack/test_serverless/tsconfig.type_check.json\n 
| 2025-06-13 13:17:30 UTC | proc [tsc]
/opt/buildkite-agent/builds/bk-agent-prod-gcp-1749820368903967112/elastic/kibana-pull-request/kibana/x-pack/solutions/security/test/tsconfig.type_check.json\n 
| 2025-06-13 13:17:30 UTC | proc [tsc]
/opt/buildkite-agent/builds/bk-agent-prod-gcp-1749820368903967112/elastic/kibana-pull-request/kibana/x-pack/test/security_solution_endpoint/tsconfig.type_check.json\n```\n\n**Important:**\nThis
PR focuses only on replacing test helpers imports
from\n`@kbn/security-solution-plugin` and `@kbn/test-suites-xpack`
in\n`osquery` plugin, no code cleanup and updates in other plugins /
test\npackages.\nWe expect code owners to update other imports /
refactor package to\navoid code
duplication\n\n---------\n\nCo-authored-by: kibanamachine
<42973632+kibanamachine@users.noreply.github.com>\nCo-authored-by:
Copilot
<175728472+Copilot@users.noreply.github.com>","sha":"539007f65aa3c9f771c8ddf5b9c9b3a766f3da22","branchLabelMapping":{"^v9.1.0$":"main","^v(\\d+).(\\d+).\\d+$":"$1.$2"}},"sourcePullRequest":{"labels":["release_note:skip","backport:skip","v9.1.0","v8.19.0"],"title":"[ska]
create platform shared package for Cypress test
helpers","number":224361,"url":"https://github.com/elastic/kibana/pull/224361","mergeCommit":{"message":"[ska]
create platform shared package for Cypress test helpers (#224361)\n\n##
Summary\n\nPart of
https://github.com/elastic/kibana-team/issues/1503\n\nThis PR adds
`kbn/cypress-test-helper` as platform shared package to\nreplace invalid
imports from private `security-solution` plugin in\nplatform shared
plugin `osquery`.\n\nThe reason is that we are **currently blocked with
x-pack relocation due\nto circular dependency**, e.g.
in\nhttps://github.com/elastic/kibana/pull/223897\n\n```\n\ninfo
starting [tsc] > node_modules/typescript/bin/tsc -b tsconfig.refs.json
--pretty\n--\n  | 2025-06-13 13:17:30 UTC | proc [tsc] error TS6202:
Project references may not form a circular graph. Cycle detected:
/opt/buildkite-agent/builds/bk-agent-prod-gcp-1749820368903967112/elastic/kibana-pull-request/kibana/tsconfig.refs.json\n 
| 2025-06-13 13:17:30 UTC | proc [tsc]
/opt/buildkite-agent/builds/bk-agent-prod-gcp-1749820368903967112/elastic/kibana-pull-request/kibana/x-pack/platform/plugins/shared/osquery/cypress/tsconfig.type_check.json\n 
| 2025-06-13 13:17:30 UTC | proc [tsc]
/opt/buildkite-agent/builds/bk-agent-prod-gcp-1749820368903967112/elastic/kibana-pull-request/kibana/x-pack/test_serverless/tsconfig.type_check.json\n 
| 2025-06-13 13:17:30 UTC | proc [tsc]
/opt/buildkite-agent/builds/bk-agent-prod-gcp-1749820368903967112/elastic/kibana-pull-request/kibana/x-pack/solutions/security/test/tsconfig.type_check.json\n 
| 2025-06-13 13:17:30 UTC | proc [tsc]
/opt/buildkite-agent/builds/bk-agent-prod-gcp-1749820368903967112/elastic/kibana-pull-request/kibana/x-pack/test/security_solution_endpoint/tsconfig.type_check.json\n```\n\n**Important:**\nThis
PR focuses only on replacing test helpers imports
from\n`@kbn/security-solution-plugin` and `@kbn/test-suites-xpack`
in\n`osquery` plugin, no code cleanup and updates in other plugins /
test\npackages.\nWe expect code owners to update other imports /
refactor package to\navoid code
duplication\n\n---------\n\nCo-authored-by: kibanamachine
<42973632+kibanamachine@users.noreply.github.com>\nCo-authored-by:
Copilot
<175728472+Copilot@users.noreply.github.com>","sha":"539007f65aa3c9f771c8ddf5b9c9b3a766f3da22"}},"sourceBranch":"main","suggestedTargetBranches":["8.19"],"targetPullRequestStates":[{"branch":"main","label":"v9.1.0","branchLabelMappingKey":"^v9.1.0$","isSourceBranch":true,"state":"MERGED","url":"https://github.com/elastic/kibana/pull/224361","number":224361,"mergeCommit":{"message":"[ska]
create platform shared package for Cypress test helpers (#224361)\n\n##
Summary\n\nPart of
https://github.com/elastic/kibana-team/issues/1503\n\nThis PR adds
`kbn/cypress-test-helper` as platform shared package to\nreplace invalid
imports from private `security-solution` plugin in\nplatform shared
plugin `osquery`.\n\nThe reason is that we are **currently blocked with
x-pack relocation due\nto circular dependency**, e.g.
in\nhttps://github.com/elastic/kibana/pull/223897\n\n```\n\ninfo
starting [tsc] > node_modules/typescript/bin/tsc -b tsconfig.refs.json
--pretty\n--\n  | 2025-06-13 13:17:30 UTC | proc [tsc] error TS6202:
Project references may not form a circular graph. Cycle detected:
/opt/buildkite-agent/builds/bk-agent-prod-gcp-1749820368903967112/elastic/kibana-pull-request/kibana/tsconfig.refs.json\n 
| 2025-06-13 13:17:30 UTC | proc [tsc]
/opt/buildkite-agent/builds/bk-agent-prod-gcp-1749820368903967112/elastic/kibana-pull-request/kibana/x-pack/platform/plugins/shared/osquery/cypress/tsconfig.type_check.json\n 
| 2025-06-13 13:17:30 UTC | proc [tsc]
/opt/buildkite-agent/builds/bk-agent-prod-gcp-1749820368903967112/elastic/kibana-pull-request/kibana/x-pack/test_serverless/tsconfig.type_check.json\n 
| 2025-06-13 13:17:30 UTC | proc [tsc]
/opt/buildkite-agent/builds/bk-agent-prod-gcp-1749820368903967112/elastic/kibana-pull-request/kibana/x-pack/solutions/security/test/tsconfig.type_check.json\n 
| 2025-06-13 13:17:30 UTC | proc [tsc]
/opt/buildkite-agent/builds/bk-agent-prod-gcp-1749820368903967112/elastic/kibana-pull-request/kibana/x-pack/test/security_solution_endpoint/tsconfig.type_check.json\n```\n\n**Important:**\nThis
PR focuses only on replacing test helpers imports
from\n`@kbn/security-solution-plugin` and `@kbn/test-suites-xpack`
in\n`osquery` plugin, no code cleanup and updates in other plugins /
test\npackages.\nWe expect code owners to update other imports /
refactor package to\navoid code
duplication\n\n---------\n\nCo-authored-by: kibanamachine
<42973632+kibanamachine@users.noreply.github.com>\nCo-authored-by:
Copilot
<175728472+Copilot@users.noreply.github.com>","sha":"539007f65aa3c9f771c8ddf5b9c9b3a766f3da22"}},{"branch":"8.19","label":"v8.19.0","branchLabelMappingKey":"^v(\\d+).(\\d+).\\d+$","isSourceBranch":false,"state":"NOT_CREATED"}]}]
BACKPORT-->