[8.7] [Security Solution] [Analyzer] Use correct unmapped type for tiebreaker (#153480) (#153507)
# Backport

This will backport the following commits from `main` to `8.7`:
- [[Security Solution] [Analyzer] Use correct unmapped type for
tiebreaker (#153480)](https://github.com/elastic/kibana/pull/153480)

<!--- Backport version: 8.9.7 -->

### Questions ?
Please refer to the [Backport tool
documentation](https://github.com/sqren/backport)

<!--BACKPORT [{"author":{"name":"Kevin
Qualters","email":"56408403+kqualters-elastic@users.noreply.github.com"},"sourceCommit":{"committedDate":"2023-03-22T23:16:45Z","message":"[Security
Solution] [Analyzer] Use correct unmapped type for tiebreaker
(#153480)\n\n## Summary\r\n\r\nRelated issue:
https://github.com/elastic/kibana/issues/153189\r\n\r\nFixes an issue
where when using analyzer with an integration that did\r\nnot map
event.id, the unmapped_type on this changed line was wrong,
as\r\nnormally this field is a keyword. This would cause the analyzer
events\r\napi request to fail with\r\n```\r\nResponseError:
search_phase_execution_exception\r\n Caused by:\r\n
illegal_argument_exception: Can't sort on field [__anonymous_]; the
field has incompatible sort types: [STRING] and [LONG] across
shards!\r\n Root causes:\r\n task_cancelled_exception: parent task was
cancelled [Fatal failure during search: failed to merge result [Can't
sort on field [__anonymous_]; the field has incompatible sort types:
[STRING] and [LONG] across
shards!]]\r\n```\r\nBefore:\r\n\r\n![image](https://user-images.githubusercontent.com/56408403/226994873-f8a23051-3d00-4974-b4a3-06b6fffa2b4e.png)\r\nAfter:\r\n\r\n![image](https://user-images.githubusercontent.com/56408403/226994908-284efbe7-3599-4aca-aef6-f0cb43f91ce8.png)\r\n\r\n\r\n###
Checklist\r\n\r\n- [ ] [Unit or
functional\r\ntests](https://www.elastic.co/guide/en/kibana/master/development-tests.html)\r\nwere
updated or added to match the most common
scenarios","sha":"c333ca62e6b646348c1808c4e8cfccb621c8d485","branchLabelMapping":{"^v8.8.0$":"main","^v(\\d+).(\\d+).\\d+$":"$1.$2"}},"sourcePullRequest":{"labels":["release_note:skip","Team:Threat
Hunting:Investigations","v8.7.0","v8.8.0"],"number":153480,"url":"https://github.com/elastic/kibana/pull/153480","mergeCommit":{"message":"[Security
Solution] [Analyzer] Use correct unmapped type for tiebreaker
(#153480)\n\n## Summary\r\n\r\nRelated issue:
https://github.com/elastic/kibana/issues/153189\r\n\r\nFixes an issue
where when using analyzer with an integration that did\r\nnot map
event.id, the unmapped_type on this changed line was wrong,
as\r\nnormally this field is a keyword. This would cause the analyzer
events\r\napi request to fail with\r\n```\r\nResponseError:
search_phase_execution_exception\r\n Caused by:\r\n
illegal_argument_exception: Can't sort on field [__anonymous_]; the
field has incompatible sort types: [STRING] and [LONG] across
shards!\r\n Root causes:\r\n task_cancelled_exception: parent task was
cancelled [Fatal failure during search: failed to merge result [Can't
sort on field [__anonymous_]; the field has incompatible sort types:
[STRING] and [LONG] across
shards!]]\r\n```\r\nBefore:\r\n\r\n![image](https://user-images.githubusercontent.com/56408403/226994873-f8a23051-3d00-4974-b4a3-06b6fffa2b4e.png)\r\nAfter:\r\n\r\n![image](https://user-images.githubusercontent.com/56408403/226994908-284efbe7-3599-4aca-aef6-f0cb43f91ce8.png)\r\n\r\n\r\n###
Checklist\r\n\r\n- [ ] [Unit or
functional\r\ntests](https://www.elastic.co/guide/en/kibana/master/development-tests.html)\r\nwere
updated or added to match the most common
scenarios","sha":"c333ca62e6b646348c1808c4e8cfccb621c8d485"}},"sourceBranch":"main","suggestedTargetBranches":["8.7"],"targetPullRequestStates":[{"branch":"8.7","label":"v8.7.0","labelRegex":"^v(\\d+).(\\d+).\\d+$","isSourceBranch":false,"state":"NOT_CREATED"},{"branch":"main","label":"v8.8.0","labelRegex":"^v8.8.0$","isSourceBranch":true,"state":"MERGED","url":"https://github.com/elastic/kibana/pull/153480","number":153480,"mergeCommit":{"message":"[Security
Solution] [Analyzer] Use correct unmapped type for tiebreaker
(#153480)\n\n## Summary\r\n\r\nRelated issue:
https://github.com/elastic/kibana/issues/153189\r\n\r\nFixes an issue
where when using analyzer with an integration that did\r\nnot map
event.id, the unmapped_type on this changed line was wrong,
as\r\nnormally this field is a keyword. This would cause the analyzer
events\r\napi request to fail with\r\n```\r\nResponseError:
search_phase_execution_exception\r\n Caused by:\r\n
illegal_argument_exception: Can't sort on field [__anonymous_]; the
field has incompatible sort types: [STRING] and [LONG] across
shards!\r\n Root causes:\r\n task_cancelled_exception: parent task was
cancelled [Fatal failure during search: failed to merge result [Can't
sort on field [__anonymous_]; the field has incompatible sort types:
[STRING] and [LONG] across
shards!]]\r\n```\r\nBefore:\r\n\r\n![image](https://user-images.githubusercontent.com/56408403/226994873-f8a23051-3d00-4974-b4a3-06b6fffa2b4e.png)\r\nAfter:\r\n\r\n![image](https://user-images.githubusercontent.com/56408403/226994908-284efbe7-3599-4aca-aef6-f0cb43f91ce8.png)\r\n\r\n\r\n###
Checklist\r\n\r\n- [ ] [Unit or
functional\r\ntests](https://www.elastic.co/guide/en/kibana/master/development-tests.html)\r\nwere
updated or added to match the most common
scenarios","sha":"c333ca62e6b646348c1808c4e8cfccb621c8d485"}}]}]
BACKPORT-->

Co-authored-by: Kevin Qualters <56408403+kqualters-elastic@users.noreply.github.com>