[streams_app][scout] improve edit_processor tests (#236132)
## Summary

We saw some failures on `main` and searching in DOM for a text without
target element (like `page.getByText('%{WORD:attributes.method}')`) is
generally not recommended.

```
Error: expect.toBeVisible: Error: strict mode violation: getByText('%{WORD:attributes.method}') resolved to 2 elements:
    1) <div class="euiText css-1t8j3hh-euiText-s-euiTextColor-subdued">%{WORD:attributes.method}</div> aka getByTestId('truncatedText').getByText('%{WORD:attributes.method}')
    2) <span data-test-subj="fullText" class="euiTextTruncate__fullText css-qkfygu-euiTextTruncate__fullText">%{WORD:attributes.method}</span> aka getByTestId('fullText')

Call log:
  - Expect "toBeVisible" with timeout 10000ms
  - waiting for getByText('%{WORD:attributes.method}')

    at x-pack/platform/plugins/shared/streams_app/test/scout/ui/tests/data_management/data_processing/edit_processor.spec.ts:34:63
```

I ran these tests with updates locally 10x time in a loop and no longer
can see the failure.

---------

Co-authored-by: kibanamachine <42973632+kibanamachine@users.noreply.github.com>