[8.19] [ci] Lint yamls upon commit (#235181) (#235328)
# Backport

This will backport the following commits from `main` to `8.19`:
- [[ci] Lint yamls upon commit
(#235181)](https://github.com/elastic/kibana/pull/235181)

<!--- Backport version: 9.6.6 -->

### Questions ?
Please refer to the [Backport tool
documentation](https://github.com/sorenlouv/backport)

<!--BACKPORT [{"author":{"name":"Alex
Szabo","email":"alex.szabo@elastic.co"},"sourceCommit":{"committedDate":"2025-09-17T08:56:58Z","message":"[ci]
Lint yamls upon commit (#235181)\n\n## Summary\nWe've seen earlier where
we've edited yaml files, and managed to push\nthem with some syntax
issues. This adds a safeguard locally to try to\navoid those
issues.\n\n- Refactors `run_precommit_hook.js` to allow for more
checks\n- Adds a yaml linting step to the pre-commit hook\n- (unrelated)
Clarifies missing bootstrap error (*)\n\n\n(*)\nIf you've wanted to get
the TS project list after a branch switch, it\ngave this
error:\n```\nts_project.ts:48\n matches: knownPaths.filter(matcher),\n
^\nTypeError: knownPaths.filter is not a function\n at map
(ts_project.ts:48:25)\n```\nMeaning, you should re-bootstrap. It's now
more explicit with an error:\n```\nts_project.ts:76\n throw new
Error('TS Project map missing, make sure you run `yarn kbn
bootstrap`');\n ^\nError: TS Project map missing, make sure you run
`yarn kbn bootstrap`\n at Function.loadAll
(ts_project.ts:76:13)\n```\n\n---------\n\nCo-authored-by: Copilot
<175728472+Copilot@users.noreply.github.com>","sha":"7bca91c3e415608574ad94d62f0c78b6ef136003","branchLabelMapping":{"^v9.2.0$":"main","^v(\\d+).(\\d+).\\d+$":"$1.$2"}},"sourcePullRequest":{"labels":["Team:Operations","release_note:skip","backport:all-open","v9.2.0"],"title":"[ci]
Lint yamls upon
commit","number":235181,"url":"https://github.com/elastic/kibana/pull/235181","mergeCommit":{"message":"[ci]
Lint yamls upon commit (#235181)\n\n## Summary\nWe've seen earlier where
we've edited yaml files, and managed to push\nthem with some syntax
issues. This adds a safeguard locally to try to\navoid those
issues.\n\n- Refactors `run_precommit_hook.js` to allow for more
checks\n- Adds a yaml linting step to the pre-commit hook\n- (unrelated)
Clarifies missing bootstrap error (*)\n\n\n(*)\nIf you've wanted to get
the TS project list after a branch switch, it\ngave this
error:\n```\nts_project.ts:48\n matches: knownPaths.filter(matcher),\n
^\nTypeError: knownPaths.filter is not a function\n at map
(ts_project.ts:48:25)\n```\nMeaning, you should re-bootstrap. It's now
more explicit with an error:\n```\nts_project.ts:76\n throw new
Error('TS Project map missing, make sure you run `yarn kbn
bootstrap`');\n ^\nError: TS Project map missing, make sure you run
`yarn kbn bootstrap`\n at Function.loadAll
(ts_project.ts:76:13)\n```\n\n---------\n\nCo-authored-by: Copilot
<175728472+Copilot@users.noreply.github.com>","sha":"7bca91c3e415608574ad94d62f0c78b6ef136003"}},"sourceBranch":"main","suggestedTargetBranches":[],"targetPullRequestStates":[{"branch":"main","label":"v9.2.0","branchLabelMappingKey":"^v9.2.0$","isSourceBranch":true,"state":"MERGED","url":"https://github.com/elastic/kibana/pull/235181","number":235181,"mergeCommit":{"message":"[ci]
Lint yamls upon commit (#235181)\n\n## Summary\nWe've seen earlier where
we've edited yaml files, and managed to push\nthem with some syntax
issues. This adds a safeguard locally to try to\navoid those
issues.\n\n- Refactors `run_precommit_hook.js` to allow for more
checks\n- Adds a yaml linting step to the pre-commit hook\n- (unrelated)
Clarifies missing bootstrap error (*)\n\n\n(*)\nIf you've wanted to get
the TS project list after a branch switch, it\ngave this
error:\n```\nts_project.ts:48\n matches: knownPaths.filter(matcher),\n
^\nTypeError: knownPaths.filter is not a function\n at map
(ts_project.ts:48:25)\n```\nMeaning, you should re-bootstrap. It's now
more explicit with an error:\n```\nts_project.ts:76\n throw new
Error('TS Project map missing, make sure you run `yarn kbn
bootstrap`');\n ^\nError: TS Project map missing, make sure you run
`yarn kbn bootstrap`\n at Function.loadAll
(ts_project.ts:76:13)\n```\n\n---------\n\nCo-authored-by: Copilot
<175728472+Copilot@users.noreply.github.com>","sha":"7bca91c3e415608574ad94d62f0c78b6ef136003"}}]}]
BACKPORT-->

Co-authored-by: Alex Szabo <alex.szabo@elastic.co>
Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>