[Integrations Manager] Initial plugin (#37950)
Most of the code is only a bit beyond "Hello World" but it's a start. Here's an overview of what each file does right now

```
> tree x-pack/plugins/integrations_manager/
x-pack/plugins/integrations_manager/
├── common 
│   ├── constants.ts        # common strings, mostly. id, paths, etc
│   └── types.ts            # as we find common types
├── index.ts                # legacy plugin definition
├── kibana.json             # new platform style shown in MIGRATION.md
├── public
│   ├── components          # plugin-specific components (used by screens/*)
│   ├── data.ts             # all client-side data fetching
│   ├── index.tsx           # React root. Client-side routes applied
│   ├── register_feature.ts # add to registry for /#/home/feature_directory
│   ├── routes.tsx          # every re: client-side routes. paths, mappings
│   └── screens             # typically a view for a client-side route
│       ├── detail.tsx      # integration detail view i.e. '/detail/:pkgkey'
│       └── home.tsx        # integration list view i.e. '/'
└── server            
    ├── index.ts            # new platform style shown in MIGRATION.md 
    ├── plugin.ts           # new platform style shown in MIGRATION.md
    ├── registry.ts         # anything registry-related
    ├── routes.ts           # every re: server-side routes. paths, mappings
    └── saved_objects.ts    # anything saved objects-related

5 directories, 16 files
```
### Summary
  - mounted under `/app/integrations_manager`
  - Integrations Manager communicates with [Registry](https://github.com/elastic/integrations-registry) (currently on localhost 8080)
  - <details><summary>quick pass at List & Detail views</summary>

    <img width="1067" alt="Screen Shot 2019-05-28 at 11 11 49 AM" src="https://user-images.githubusercontent.com/57655/58489610-9ab23500-8139-11e9-8774-d4946526ce65.png"><img width="1064" alt="Screen Shot 2019-05-28 at 11 12 50 AM" src="https://user-images.githubusercontent.com/57655/58489609-9ab23500-8139-11e9-9d7c-2ebce1f85ba8.png">
</details>

  - nav icon is placeholder/incorrect
  - using Saved Objects client

### Commits
* Basic baseline integrations manager plugin added to Kibana

* Use a consistent schame for path

* WIP. Manger can make requests to Registry.

Tough day today. Went sideways with https://elastic.slack.com/archives/CCJQY1NS0/p1558460667396200

Not sure how server will make external requests or much about it's API. Put a quick skeleton up to show we can fetch data from registry service (optionally act on it) and respond.

* Fix plugin definition to avoid security plugin error re: invalid ID.

* Fix linter errors

* Move routes to own file. Extract plugin ID to const/file.

* Mirror (?) plugin pattern shown in migration docs.

* WIP. Have master & detail view (sort of)

* Move manager's paths to `common/constants`. Fix linter issues.

* Use library fn to create relative paths. Move app paths to `constants.ts`

* Add data fetching with `axios` & Hooks. Some refactoring/consolidation.

Moved components from `public/routes` to new `screens` & `components` directories. `public/routes` is now array of React Elements vs JS Objects

Added `public/data` which has functions to get data (our API, maybe cache/transform response). Used `axios` because it supports promises & was already installed

Created `common/types`

* Small whitespace/typography improvements(?)

* Support for `basePath`. Explicitly import registry functions we need.

* Fetch zip from registry & extract locally. Return file paths as example.

Fetches on each request at the moment. Trivial to convert to fetch-if-missing later.

* Only fetch package if it hasn't been fetched/inflated already.

Not sure about the names/functions here, but the ideas are sound.

* Remove client-side routes from `common`. Only API is needed by both sides

* WIP. API & Types around Saved Objects are junk but work for now

* Fix(?) GH check fail. Some type shuffling/consolidation.

CI failure: https://github.com/elastic/kibana/pull/37950/checks?check_run_id=141144417

* Get Saved Objects client from `Request` type instead of `Server`.

Remove some unused types/interfaces

* Towards New Platform. Add `kibana.json`. Split `server/{index,plugin}`

* GH CI can't find `@kbn/es/src/utils`. Copied `decompress` locally for now

* Remove unused variable

* Remove stray console.log's

* Fix(?) CI failures? Move a `LegacyPluginInitializer` to `common/types`

* Fix error re: missing kibana.json version. More registry response types.

* More accurate(?) definition. Want list of multiple items; not just one.

* Use `ALWAYS_COMPATIBLE_VERSION` for `version` in `kibana.json`

Previous CI run complained about a missing version, so I set to `"0.0.2"` thinking I was versioning _the plugin_

A subsequent CI run failed with

```
Error: Failed to initialize plugins:
17:47:29 	Plugin "integrations_manager" is only compatible with Kibana version "0.0.2", but used Kibana version is "8.0.0". (incompatible-version, /var/lib/jenkins/workspace/elastic+kibana+pull-request/JOB/x-pack-intake/node/immutable/kibana/x-pack/plugins/integrations_manager/kibana.json)
```

Using the `ALWAYS_COMPATIBLE_VERSION` value from https://github.com/elastic/kibana/blob/84b595e49fa7e09b89edabdec5ba394f2d3237cb/src/core/server/plugins/discovery/plugin_manifest_parser.ts#L39 to get this to pass CI & revisit later

* Trivial change to trigger CI.

Tried "jenkins, test this" comment in GH but nothing happened.

* Address i18n feedback

* Pass `kibana.json`'s `requiredPlugins` to `new Kibana.Plugin`s `require`

Still playing with patterns, but keeping them in sync seems like A Good Thing

* Amending approach from 519a695 based on other manifests I saw.

* Don't blindly retry if can't get a package. Pass errors back to response

* Rename constant `ID` to more explicit `PLUGIN_ID`

* Update x-pack/plugins/integrations_manager/index.ts

Co-Authored-By: Felix Stürmer <weltenwort@users.noreply.github.com>

* Update x-pack/plugins/integrations_manager/index.ts

Co-Authored-By: Felix Stürmer <weltenwort@users.noreply.github.com>

* Update x-pack/plugins/integrations_manager/index.ts

Co-Authored-By: Felix Stürmer <weltenwort@users.noreply.github.com>

* Update x-pack/plugins/integrations_manager/public/screens/detail.tsx

Co-Authored-By: Felix Stürmer <weltenwort@users.noreply.github.com>

* Update x-pack/plugins/integrations_manager/public/screens/home.tsx

Co-Authored-By: Felix Stürmer <weltenwort@users.noreply.github.com>

* Combine imports

* Added some explicit typing for Legacy Plugin. Hide unused type for now.

* WIP. Not perfect or totally done, but unzip to memory (Map) vs fs.

```
> http -a elastic:changeme -A basic GET :5601/api/integrations_manager/package/envoyproxy-0.0.5/get
HTTP/1.1 200 OK
Date: Fri, 07 Jun 2019 21:55:02 GMT
Transfer-Encoding: chunked
cache-control: no-cache
connection: close
content-encoding: gzip
content-type: application/json; charset=utf-8
kbn-name: kibana
kbn-xpack-sig: 9b2bee4e36b2242b4c157c665bf740e6
vary: origin,accept-encoding

{
    "meta": {
        "paths": [
            "ENVOYPROXY-0.0.5/",
            "ENVOYPROXY-0.0.5/KIBANA/",
            "ENVOYPROXY-0.0.5/KIBANA/VISUALIZATION/",
            "ENVOYPROXY-0.0.5/KIBANA/VISUALIZATION/7E4084E0-5C99-11E9-8477-077EC9664DBD.JSON",
            "ENVOYPROXY-0.0.5/KIBANA/VISUALIZATION/0A994AF0-5C9D-11E9-8477-077EC9664DBD.JSON",
            "ENVOYPROXY-0.0.5/KIBANA/VISUALIZATION/36F872A0-5C03-11E9-85B4-19D0072EB4F2.JSON",
            "ENVOYPROXY-0.0.5/KIBANA/VISUALIZATION/38F96190-5C99-11E9-8477-077EC9664DBD.JSON",
            "ENVOYPROXY-0.0.5/KIBANA/VISUALIZATION/80844540-5C97-11E9-8477-077EC9664DBD.JSON",
            "ENVOYPROXY-0.0.5/KIBANA/VISUALIZATION/AB48C3F0-5CA6-11E9-8477-077EC9664DBD.JSON",
            "ENVOYPROXY-0.0.5/KIBANA/SEARCH/",
            "ENVOYPROXY-0.0.5/KIBANA/DASHBOARD/",
            "ENVOYPROXY-0.0.5/KIBANA/DASHBOARD/0C610510-5CBD-11E9-8477-077EC9664DBD.JSON",
            "ENVOYPROXY-0.0.5/KIBANA/INDEX-PATTERN/",
            "ENVOYPROXY-0.0.5/KIBANA/INDEX-PATTERN/FILEBEAT-*.JSON",
            "ENVOYPROXY-0.0.5/DOCS/",
            "ENVOYPROXY-0.0.5/DOCS/DOCS.ASCIIDOC",
            "ENVOYPROXY-0.0.5/IMG/",
            "ENVOYPROXY-0.0.5/IMG/ICON.PNG",
            "ENVOYPROXY-0.0.5/IMG/KIBANA-ENVOYPROXY.JPG",
            "ENVOYPROXY-0.0.5/MANIFEST.YML",
            "ENVOYPROXY-0.0.5/ELASTICSEARCH/",
            "ENVOYPROXY-0.0.5/ELASTICSEARCH/INGEST-PIPELINE/",
            "ENVOYPROXY-0.0.5/ELASTICSEARCH/INGEST-PIPELINE/PIPELINE-JSON.JSON",
            "ENVOYPROXY-0.0.5/ELASTICSEARCH/INGEST-PIPELINE/PIPELINE-ENTRY.JSON",
            "ENVOYPROXY-0.0.5/ELASTICSEARCH/INGEST-PIPELINE/PIPELINE-TCP.JSON",
            "ENVOYPROXY-0.0.5/ELASTICSEARCH/INGEST-PIPELINE/PIPELINE-PLAINTEXT.JSON",
            "ENVOYPROXY-0.0.5/ELASTICSEARCH/INGEST-PIPELINE/PIPELINE-HTTP.JSON"
        ],
        "pkgkey": "envoyproxy-0.0.5"
    }
}
```

* Some refactoring of registry fetch/unzip. Good Enough.

```
‣ http -a elastic:changeme -A basic GET :5601/api/integrations_manager/package/envoyproxy-0.0.5/get
HTTP/1.1 200 OK
Date: Sat, 08 Jun 2019 03:40:17 GMT
Transfer-Encoding: chunked
cache-control: no-cache
connection: close
content-encoding: gzip
content-type: application/json; charset=utf-8
kbn-name: kibana
kbn-xpack-sig: 9b2bee4e36b2242b4c157c665bf740e6
vary: origin,accept-encoding

{
    "meta": {
        "paths": [
            "/",
            "/kibana/",
            "/kibana/visualization/",
            "/kibana/visualization/7e4084e0-5c99-11e9-8477-077ec9664dbd.json",
            "/kibana/visualization/0a994af0-5c9d-11e9-8477-077ec9664dbd.json",
            "/kibana/visualization/36f872a0-5c03-11e9-85b4-19d0072eb4f2.json",
            "/kibana/visualization/38f96190-5c99-11e9-8477-077ec9664dbd.json",
            "/kibana/visualization/80844540-5c97-11e9-8477-077ec9664dbd.json",
            "/kibana/visualization/ab48c3f0-5ca6-11e9-8477-077ec9664dbd.json",
            "/kibana/search/",
            "/kibana/dashboard/",
            "/kibana/dashboard/0c610510-5cbd-11e9-8477-077ec9664dbd.json",
            "/kibana/index-pattern/",
            "/kibana/index-pattern/filebeat-*.json",
            "/docs/",
            "/docs/docs.asciidoc",
            "/img/",
            "/img/icon.png",
            "/img/kibana-envoyproxy.jpg",
            "/manifest.yml",
            "/elasticsearch/",
            "/elasticsearch/ingest-pipeline/",
            "/elasticsearch/ingest-pipeline/pipeline-json.json",
            "/elasticsearch/ingest-pipeline/pipeline-entry.json",
            "/elasticsearch/ingest-pipeline/pipeline-tcp.json",
            "/elasticsearch/ingest-pipeline/pipeline-plaintext.json",
            "/elasticsearch/ingest-pipeline/pipeline-http.json"
        ],
        "pkgkey": "envoyproxy-0.0.5"
    }
}
```

* Address CI failure. Remove unused variable. Fixed/changed a common type.

* Extract `core.http` interface to `HttpServiceSetup`

* Address PR feedback re: unnecessary catch & re-throw.

* Remove unused export. Trigger CI

* Add ServerRoute type to server/routes export

* Fix (?) CI error re: `build_renovate_config` script & `renovate.json5`.

e.g. https://kibana-ci.elastic.co/job/elastic+kibana+pull-request/JOB=kibana-intake,node=immutable/1413/console

```
11:12:59  -- building renovate config
11:13:01
11:13:01 ERROR: 'node scripts/build_renovate_config' caused changes to the following files:
11:13:01
11:13:01 renovate.json5
```