[Security Solution] Skips failing EQL test in MKI (#188672)
Raised an issue to unskip in test :
https://github.com/elastic/kibana/issues/188734

This PR simple skips a test failing in MKI Build. Build link & logs can
be found below:

Build link:
https://buildkite.com/elastic/kibana-serverless-security-solution-quality-gate-detection-engine/builds/845#0190c5bd-7072-4c35-a6af-48f4dda768a4

Logs
```
Security Solution Cypress
x-pack/test/security_solution_cypress/cypress/e2e/detection_response/detection_engine/rule_creation/eql_rule.cy·ts

EQL rules Detection rules, sequence EQL Creates and enables a new EQL rule with a sequence Creates and enables a new EQL rule with a sequence

Failures in tracked branches: 1
https://dryrun

Buildkite Job
https://buildkite.com/elastic/kibana-serverless-security-solution-quality-gate-detection-engine/builds/845#0190c5bd-7072-4c35-a6af-48f4dda768a4

AssertionError: Timed out retrying after 300000ms: Expected to find element: `[data-test-subj="eqlRuleType"]`, but never found it.
    at selectEqlRuleType (webpack:///./tasks/create_new_rule.ts:838:5)
    at Context.eval (webpack:///./e2e/detection_response/detection_engine/rule_creation/eql_rule.cy.ts:170:24)

```

(cherry picked from commit 6238d7f8533ba46634b9fe73e0a8e2e490a3f8b3)