[Discover] fix time picker related flacky test (#292270)
- Closes https://github.com/elastic/kibana/issues/266279

## Summary
Fixes
```
Error: timed out waiting for endDate is set to Sep 23, 2015 @ 18:31:44.000 -- last error: Error: retry.try reached timeout 120000 ms
TimeoutError: Waiting for element to be located By(css selector, [data-test-subj="superDatePickerendDatePopoverButton"])
Wait timed out after 10050ms
```
Rewrote `showStartEndTimes `to retry until the popover buttons are
actually shown, supporting clients thats renders a disable button while
loading.

### Checklist
- [x] [Flaky Test
Runner](https://ci-stats.kibana.dev/trigger_flaky_test_runner/1) was
used on any tests changed

(cherry picked from commit 0558f3a53a07679e445fbcce9d72902b06476851)