[Obs AI Assistant] Do not attempt to overwrite index mappings if inference id in component template has changed (#220739)
Improve flaky API tests and avoid errors like:

```
[ERROR][plugins.observabilityAIAssistant.service] Failed to PUT mapping for .kibana-observability-ai-assistant-kb: illegal_argument_exception
 	Root causes:
 		illegal_argument_exception: Mapper for [semantic_text] conflicts with existing mapper:
 	Cannot update parameter [inference_id] from [pt_tiny_elser_inference_id] to [pt_tiny_text_embedding_inference_id]
```