[8.19] Audit Synthetics plugin log levels (#218399) (#223872)
# Backport

This will backport the following commits from `main` to `8.19`:
- [Audit Synthetics plugin log levels
(#218399)](https://github.com/elastic/kibana/pull/218399)

<!--- Backport version: 10.0.0 -->

### Questions ?
Please refer to the [Backport tool
documentation](https://github.com/sorenlouv/backport)

<!--BACKPORT [{"author":{"name":"Maryam
Saeidi","email":"maryam.saeidi@elastic.co"},"sourceCommit":{"committedDate":"2025-06-12T13:55:03Z","message":"Audit
Synthetics plugin log levels (#218399)\n\nCloses
https://github.com/elastic/observability-dev/issues/4432\n\n##
Summary\n\nAuditing
[log\nlevels](https://docs.elastic.dev/kibana-dev-docs/services/logging#log-level)\nin
the Synthetics plugin.\n\n### Example\nThrowing error when creating a
new
monitor:\n<img\nsrc=\"https://github.com/user-attachments/assets/7cead63b-c209-4174-a4f7-7dfad40aa34d\"\nwidth=500
/>\n\n####
Before\n```\n1.\n[2025-04-23T12:29:37.594+02:00][ERROR][plugins.synthetics]
Error: newMonitorPromise failed!\n at
/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:82:15\n
at async AddEditMonitorAPI.syncNewMonitor
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:88:72)\n
at async handler
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor.ts:123:11)\n\n2.\n[2025-04-23T12:29:37.595+02:00][ERROR][plugins.synthetics]
Unable to create Synthetics monitor
https://www.elastic.co/\n\n3.\n[2025-04-23T12:29:38.758+02:00][ERROR][plugins.synthetics]
Error: newMonitorPromise failed!\n at
/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:82:15\n
at async AddEditMonitorAPI.syncNewMonitor
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:88:72)\n
at async handler
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor.ts:123:11)\n\n4.\n[2025-04-23T12:29:38.760+02:00][ERROR][plugins.synthetics]
Unable to create synthetics monitor\n```\n\n####
After\n```\n[2025-05-12T16:06:23.160+02:00][ERROR][plugins.synthetics]
Unable to create Synthetics monitor with name https://www.elastic.co/
Error: newMonitorPromise failed!\n at
/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:82:15\n
at async AddEditMonitorAPI.syncNewMonitor
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:88:72)\n
at async handler
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor.ts:123:11)\n```\n#####
⚠️ Note\nAfter merging this
[PR](https://github.com/elastic/kibana/pull/219940),\nwe will also have
stacktrace locally.\n\n### ❓ Questions\n1. When calling
`synthetics/params` API with wrong parameters, we
get\n`[2025-05-13T11:05:52.401+02:00][ERROR][http] 400 Bad Request`,
which\npath is responsible for this error? (Since it is from `http`, so
it is\nnot logged in synthetics. I am wondering where the validation
is\nhappening in this case)\n**Answer**: It was
here:\nhttps://github.com/elastic/kibana/blob/main/src/core/packages/http/router-server-internal/src/route.ts#L124","sha":"327979743e08a9ae5433b3f2359817eacbfffb3d","branchLabelMapping":{"^v9.1.0$":"main","^v(\\d+).(\\d+).\\d+$":"$1.$2"}},"sourcePullRequest":{"labels":["release_note:skip","Team:obs-ux-management","backport:version","v9.1.0","v8.19.0"],"title":"Audit
Synthetics plugin log
levels","number":218399,"url":"https://github.com/elastic/kibana/pull/218399","mergeCommit":{"message":"Audit
Synthetics plugin log levels (#218399)\n\nCloses
https://github.com/elastic/observability-dev/issues/4432\n\n##
Summary\n\nAuditing
[log\nlevels](https://docs.elastic.dev/kibana-dev-docs/services/logging#log-level)\nin
the Synthetics plugin.\n\n### Example\nThrowing error when creating a
new
monitor:\n<img\nsrc=\"https://github.com/user-attachments/assets/7cead63b-c209-4174-a4f7-7dfad40aa34d\"\nwidth=500
/>\n\n####
Before\n```\n1.\n[2025-04-23T12:29:37.594+02:00][ERROR][plugins.synthetics]
Error: newMonitorPromise failed!\n at
/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:82:15\n
at async AddEditMonitorAPI.syncNewMonitor
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:88:72)\n
at async handler
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor.ts:123:11)\n\n2.\n[2025-04-23T12:29:37.595+02:00][ERROR][plugins.synthetics]
Unable to create Synthetics monitor
https://www.elastic.co/\n\n3.\n[2025-04-23T12:29:38.758+02:00][ERROR][plugins.synthetics]
Error: newMonitorPromise failed!\n at
/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:82:15\n
at async AddEditMonitorAPI.syncNewMonitor
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:88:72)\n
at async handler
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor.ts:123:11)\n\n4.\n[2025-04-23T12:29:38.760+02:00][ERROR][plugins.synthetics]
Unable to create synthetics monitor\n```\n\n####
After\n```\n[2025-05-12T16:06:23.160+02:00][ERROR][plugins.synthetics]
Unable to create Synthetics monitor with name https://www.elastic.co/
Error: newMonitorPromise failed!\n at
/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:82:15\n
at async AddEditMonitorAPI.syncNewMonitor
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:88:72)\n
at async handler
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor.ts:123:11)\n```\n#####
⚠️ Note\nAfter merging this
[PR](https://github.com/elastic/kibana/pull/219940),\nwe will also have
stacktrace locally.\n\n### ❓ Questions\n1. When calling
`synthetics/params` API with wrong parameters, we
get\n`[2025-05-13T11:05:52.401+02:00][ERROR][http] 400 Bad Request`,
which\npath is responsible for this error? (Since it is from `http`, so
it is\nnot logged in synthetics. I am wondering where the validation
is\nhappening in this case)\n**Answer**: It was
here:\nhttps://github.com/elastic/kibana/blob/main/src/core/packages/http/router-server-internal/src/route.ts#L124","sha":"327979743e08a9ae5433b3f2359817eacbfffb3d"}},"sourceBranch":"main","suggestedTargetBranches":["8.19"],"targetPullRequestStates":[{"branch":"main","label":"v9.1.0","branchLabelMappingKey":"^v9.1.0$","isSourceBranch":true,"state":"MERGED","url":"https://github.com/elastic/kibana/pull/218399","number":218399,"mergeCommit":{"message":"Audit
Synthetics plugin log levels (#218399)\n\nCloses
https://github.com/elastic/observability-dev/issues/4432\n\n##
Summary\n\nAuditing
[log\nlevels](https://docs.elastic.dev/kibana-dev-docs/services/logging#log-level)\nin
the Synthetics plugin.\n\n### Example\nThrowing error when creating a
new
monitor:\n<img\nsrc=\"https://github.com/user-attachments/assets/7cead63b-c209-4174-a4f7-7dfad40aa34d\"\nwidth=500
/>\n\n####
Before\n```\n1.\n[2025-04-23T12:29:37.594+02:00][ERROR][plugins.synthetics]
Error: newMonitorPromise failed!\n at
/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:82:15\n
at async AddEditMonitorAPI.syncNewMonitor
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:88:72)\n
at async handler
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor.ts:123:11)\n\n2.\n[2025-04-23T12:29:37.595+02:00][ERROR][plugins.synthetics]
Unable to create Synthetics monitor
https://www.elastic.co/\n\n3.\n[2025-04-23T12:29:38.758+02:00][ERROR][plugins.synthetics]
Error: newMonitorPromise failed!\n at
/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:82:15\n
at async AddEditMonitorAPI.syncNewMonitor
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:88:72)\n
at async handler
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor.ts:123:11)\n\n4.\n[2025-04-23T12:29:38.760+02:00][ERROR][plugins.synthetics]
Unable to create synthetics monitor\n```\n\n####
After\n```\n[2025-05-12T16:06:23.160+02:00][ERROR][plugins.synthetics]
Unable to create Synthetics monitor with name https://www.elastic.co/
Error: newMonitorPromise failed!\n at
/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:82:15\n
at async AddEditMonitorAPI.syncNewMonitor
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor/add_monitor_api.ts:88:72)\n
at async handler
(/Users/maryam.saeidi/WebstormProjects/kibana-mary/x-pack/solutions/observability/plugins/synthetics/server/routes/monitor_cruds/add_monitor.ts:123:11)\n```\n#####
⚠️ Note\nAfter merging this
[PR](https://github.com/elastic/kibana/pull/219940),\nwe will also have
stacktrace locally.\n\n### ❓ Questions\n1. When calling
`synthetics/params` API with wrong parameters, we
get\n`[2025-05-13T11:05:52.401+02:00][ERROR][http] 400 Bad Request`,
which\npath is responsible for this error? (Since it is from `http`, so
it is\nnot logged in synthetics. I am wondering where the validation
is\nhappening in this case)\n**Answer**: It was
here:\nhttps://github.com/elastic/kibana/blob/main/src/core/packages/http/router-server-internal/src/route.ts#L124","sha":"327979743e08a9ae5433b3f2359817eacbfffb3d"}},{"branch":"8.19","label":"v8.19.0","branchLabelMappingKey":"^v(\\d+).(\\d+).\\d+$","isSourceBranch":false,"state":"NOT_CREATED"}]}]
BACKPORT-->