[ResponseOps][TaskManager] event-log-ize Task Manager
resolves https://github.com/elastic/kibana/issues/229458

This PR attempts to add event log support for task manager, to have it
log `execute` and `execute-start` documents when tasks are run, similar
to what we do with rules and connectors.

Adding the code to do this is pretty straightforward, most is in the
`task_runner.ts` file.

But ... I can't get it to work.  Here's the stack trace when Kibana
dies during startup.

```
Kibana is starting
Kibana process configured with roles: [background_tasks, ui]
Kibana is shutting down
Reason: Cannot read properties of undefined (reading 'Success')
TypeError: Cannot read properties of undefined (reading 'Success')
    at Object.<anonymous> (task_run_statistics.ts:329:18)
    at Module._compile (node:internal/modules/cjs/loader:1730:14)
    at Module._compile (/Users/pmuellr/Projects/elastic/kibana-229458-event-log-for-tm/node_modules/pirates/lib/index.js:129:24)
    ...
```

I got this when I started with the existing plugins, changing the
task manager plugin to require the event log plugin.  I believe this
caused some kind of error with a dependency cycle.  I think the problem
is that event log dependes on `serverless` and `spaces`, and some of
their dependencies may depend on task manager.

So, I built a package `@kbn/event-log-types`, intended to be just the
event log types, that task manager could depend on, and then switch the
dependency so event log depends on task manager, and now the event log
setup code calls into task manager to set up the event log.  Crazy
acrobatics, and in the end, I got the same error :-)

At this point I'm stuck.