Attempt to fix flaky anomalies test on entity analytics page
Failling test:

Entity Analytics Dashboard
       With anomalies data
         renders table with pagination:
      AssertionError: Timed out retrying after 150000ms: Not enough elements found. Found '1', expected '10'.

This reverts commit d69dbe79a1a341e6346eb3978433ca66b5c094f9.