[ci] Lint yamls upon commit (#235181)
## Summary
We've seen earlier where we've edited yaml files, and managed to push
them with some syntax issues. This adds a safeguard locally to try to
avoid those issues.

- Refactors `run_precommit_hook.js` to allow for more checks
- Adds a yaml linting step to the pre-commit hook
- (unrelated) Clarifies missing bootstrap error (*)


(*)
If you've wanted to get the TS project list after a branch switch, it
gave this error:
```
ts_project.ts:48
    matches: knownPaths.filter(matcher),
                        ^
TypeError: knownPaths.filter is not a function
    at map (ts_project.ts:48:25)
```
Meaning, you should re-bootstrap. It's now more explicit with an error:
```
ts_project.ts:76
      throw new Error('TS Project map missing, make sure you run `yarn kbn bootstrap`');
            ^
Error: TS Project map missing, make sure you run `yarn kbn bootstrap`
    at Function.loadAll (ts_project.ts:76:13)
```

---------

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>