[UA] Remove `delete` from `.tasks` permission check (#203379)
## Summary

* Removes `delete` permission check on `.tasks`
* Task doc deletion best effort
* Creates a `warning` level log if deletion from `.tasks` fails like:
```
[2024-12-09T10:50:28.398+01:00][WARN ][plugins.upgradeAssistant.reindex_worker] ResponseError: security_exception
log.ts:66
	Root causes:
log.ts:66
		security_exception: action [indices:data/write/bulk[s]] is unauthorized for API key id [___] of user [elastic] on restricted indices [.tasks], this action is granted by the index privileges [create_doc,create,delete,index,write,all]
```

## How to test

1. Follow [these
steps](https://github.com/elastic/kibana-team/issues/1249#issuecomment-2514462816),
but instead of creating a data stream create an index in 7.x
2. Start ES on v8.x
3. Checkout Kibana `8.x` locally and apply [the
diff](https://patch-diff.githubusercontent.com/raw/elastic/kibana/pull/203379.diff)
from this branch
4. Start Kibana
5. Log in as `elastic` or some other admin/superuser
6. Go to UA and reindex the index you created

## Resources

### Outdated 7.x guidance


https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docs-update-by-query.html#docs-update-by-query-task-api

> When you are done with a task, you should delete the task document so
Elasticsearch can reclaim the space.