Use simplified retriever, and log requests and error responses (#247877)
## Summary

I'd noticed that when using a Search Index tool on an Alias that used a
semantic text field, I'd get errors like:
```
{
  "results": [
    {
      "tool_result_id": "s4Ygvl",
      "type": "error",
      "data": {
        "message": """Error: status_exception
	Root causes:
		status_exception: [rrf] search failed - retrievers '[standard]' returned errors. All failures are attached as suppressed exceptions.
 Please fix your mistakes."""
      }
    }
  ]
}
```


This was easily reproducible with:
```
PUT test-1
{
    "mappings": {
        "properties": {
            "test": {
                "type": "semantic_text"
            }
        }
    }
}
PUT test-1/_doc/1
{
    "test": "test"
}
PUT test-1/_alias/test
GET test/_search
{
  "size": 10,
    "retriever": {
        "rrf": {
        "rank_window_size": 20,
        "retrievers": [
            {
            "standard": {
                "query": {
                "multi_match": {
                    "query": "test",
                    "fields": [
                    "test"
                    ]
                }
                }
            }
            }
        ]
        }
    },
    "highlight": {
        "number_of_fragments": 5,
        "fields": {
        "test": {}
        }
    }
}
```

@pgayvallet realized that we had a logical error, where using
`field_caps` with aliases lead to semantic_text fields being
mis-identified as text fields.

@kderusso suggested that we could avoid this separate handling, because
with the new simplified retriever format, both field types can be
handled the same way.

This PR swiches us to that simplified retriever format, and also
introduces a logger to capture the request and any error responses, for
better debugging in the future.

### Release note
Fixes a bug where Agent Builder Index Search tools would fail on aliases
that contained semantic_text fields