Quick-fix Users can’t upgrade their clusters when `riskScore` experimental feature is enabled (#146780)
Users can't upgrade their clusters when an old experimental feature is
enabled.

While we don't have a final solution for this issue, I am adding the
experimental flag configuration back to prevent users from having this
frustrating experience.

Quick-fix for: https://github.com/elastic/kibana/issues/146777
Original report:
https://elastic.slack.com/archives/C6E3MTCD7/p1669236299374339

Fix
```
FATAL Error: [config validation of [xpack.securitySolution].enableExperimental]: [riskyUsersEnabled] is not allowed. Allowed values are: tGridEnabled, tGridEventRenderedViewEnabled, excludePoliciesInFilterEnabled, kubernetesEnabled, disableIsolationUIPendingStatuses, pendingActionResponsesWithAck, policyListEnabled, policyResponseInFleetEnabled, previewTelemetryUrlEnabled, responseActionsConsoleEnabled, insightsRelatedAlertsByProcessAncestry, extendedRuleExecutionLoggingEnabled, socTrendsEnabled, responseActionsEnabled
```

Co-authored-by: Kibana Machine <42973632+kibanamachine@users.noreply.github.com>
(cherry picked from commit c3d1d9ec284f81f3c5d713010e52cd9d4f09c39e)

# Conflicts:
#	x-pack/plugins/security_solution/common/experimental_features.ts