[OneChat] Check if text or semantic_text fields exist before executing match search (#234089)
## Summary

This PR adds a check inside `relevance_search` to ensure `text` or
`semantic_text` fields actually exist, and throws an `Error` if none are
found, thus preventing an attempt at an RRF query that would otherwise
fail.

Example output with the proposed changes:
```JSON
{
  "results": [
    {
      "type": "error",
      "data": {
        "message": """Error: No text or semantic_text fields found, aborting search.
 Please fix your mistakes."""
      }
    }
  ]
}
```

The old output, for reference. The RRF query was attempted with no
`text` or `semantic_text` fields, which caused the esClient to throw an
error that gets propagated up.
```JSON
{
  "results": [
    {
      "type": "error",
      "data": {
        "message": """Error: action_request_validation_exception
	Root causes:
		action_request_validation_exception: Validation Failed: 1: [rrf] must provide [retrievers] or [query];
 Please fix your mistakes."""
      }
    }
  ]
}

```
Closes https://github.com/elastic/search-team/issues/10912

### Checklist

Check the PR satisfies following conditions. 

Reviewers should verify this PR satisfies this list as well.

- [ ] Any text added follows [EUI's writing
guidelines](https://elastic.github.io/eui/#/guidelines/writing), uses
sentence case text and includes [i18n
support](https://github.com/elastic/kibana/blob/main/src/platform/packages/shared/kbn-i18n/README.md)
- [ ]
[Documentation](https://www.elastic.co/guide/en/kibana/master/development-documentation.html)
was added for features that require explanation or tutorials
- [ ] [Unit or functional
tests](https://www.elastic.co/guide/en/kibana/master/development-tests.html)
were updated or added to match the most common scenarios
- [ ] If a plugin configuration key changed, check if it needs to be
allowlisted in the cloud and added to the [docker
list](https://github.com/elastic/kibana/blob/main/src/dev/build/tasks/os_packages/docker_generator/resources/base/bin/kibana-docker)
- [ ] This was checked for breaking HTTP API changes, and any breaking
changes have been approved by the breaking-change committee. The
`release_note:breaking` label should be applied in these situations.
- [ ] [Flaky Test
Runner](https://ci-stats.kibana.dev/trigger_flaky_test_runner/1) was
used on any tests changed
- [ ] The PR description includes the appropriate Release Notes section,
and the correct `release_note:*` label is applied per the
[guidelines](https://www.elastic.co/guide/en/kibana/master/contributing.html#kibana-release-notes-process)
- [ ] Review the [backport
guidelines](https://docs.google.com/document/d/1VyN5k91e5OVumlc0Gb9RPa3h1ewuPE705nRtioPiTvY/edit?usp=sharing)
and apply applicable `backport:*` labels.

### Identify risks

Does this PR introduce any risks? For example, consider risks like hard
to test bugs, performance regression, potential of data loss.

Describe the risk, its severity, and mitigation for each identified
risk. Invite stakeholders and evaluate how to proceed before merging.

- [ ] [See some risk
examples](https://github.com/elastic/kibana/blob/main/RISK_MATRIX.mdx)
- [ ] ...

---------

Co-authored-by: kibanamachine <42973632+kibanamachine@users.noreply.github.com>