fix failing security_solution scout test on ECH (#250915)
## Summary

Unfortunately the original fix didn't work well against ECH in the long
run. This time I changed how assertion is done and how row is located.

Verified locally against 9.4-snapshot.

```
Error: Alert with rule 'Alert Testing Query_test-space-2_1769689348376' is not displayed in the alerts table

expect(locator).toBeVisible() failed

Locator: locator('[data-test-subj="alertsTableIsLoaded"]').locator('div.euiDataGridRow').filter({ hasText: 'Alert Testing Query_test-space-2_1769689348376' })
Expected: visible
Error: strict mode violation: locator('[data-test-subj="alertsTableIsLoaded"]').locator('div.euiDataGridRow').filter({ hasText: 'Alert Testing Query_test-space-2_1769689348376' }) resolved to 3 elements:
    1) <div role="row" class="euiDataGridRow" data-grid-row-index="0" data-grid-visible-row-index="0">…</div> aka getByRole('row', { name: 'Select row 1 View details for' })
    2) <div role="row" data-grid-row-index="1" data-grid-visible-row-index="1" class="euiDataGridRow euiDataGridRow--striped">…</div> aka getByRole('row', { name: 'Select row 2 View details for' })
    3) <div role="row" class="euiDataGridRow" data-grid-row-index="2" data-grid-visible-row-index="2">…</div> aka getByRole('row', { name: 'Select row 3 View details for' })

Call log:
  - Alert with rule 'Alert Testing Query_test-space-2_1769689348376' is not displayed in the alerts table with timeout 10000ms
  - waiting for locator('[data-test-subj="alertsTableIsLoaded"]').locator('div.euiDataGridRow').filter({ hasText: 'Alert Testing Query_test-space-2_1769689348376' })

    at Proxy.expandAlertDetailsFlyout (x-pack/solutions/security/packages/kbn-scout-security/src/playwright/fixtures/test/page_objects/alerts_table.ts:35:7)
    at x-pack/solutions/security/plugins/security_solution/test/scout/ui/parallel_tests/flyout/alert_details_url_sync.spec.ts:32:5
```

---------

Co-authored-by: kibanamachine <42973632+kibanamachine@users.noreply.github.com>