[scout] fix flaky streams "discover integration" tests on MKI (#250396)
## Summary

Fixing 2 flaky tests on MKI:

```
[serverless-oblt - Discover integration - Classic Stream - Navigate to Stream processing from document flyout - should navigate to Stream processing page from Discover document flyout in ES|QL mode]
[serverless-oblt - Discover integration - Wired Stream - Navigate to Stream processing from document flyout - should navigate to Stream processing page from Discover document flyout in ES|QL mode]
```

Error
```ts
Error: expect(locator).toBeVisible() failed

Locator: locator('[data-test-subj="kbnDocViewer"]')
Expected: visible
Timeout: 30000ms
Error: element(s) not found

Call log:
  - Expect "toBeVisible" with timeout 30000ms
  - waiting for locator('[data-test-subj="kbnDocViewer"]')

    at Proxy.waitForDocViewerFlyoutOpen (src/platform/packages/shared/kbn-scout/src/playwright/page_objects/discover_app.ts:127:29)
    at x-pack/platform/plugins/shared/streams_app/test/scout/ui/tests/discover_integration_classic.spec.ts:115:34
```

<img width="1280" height="720" alt="image"
src="https://github.com/user-attachments/assets/7b2f0ed6-9ad5-4139-a295-4096b97f5689"
/>

Another change to timepicker selection, it also failed on MKI

Tested in
https://buildkite.com/elastic/appex-qa-serverless-kibana-scout-tests/builds/117#_

---------

Co-authored-by: kibanamachine <42973632+kibanamachine@users.noreply.github.com>
(cherry picked from commit eb6e38cb5963a610584f09d5e0eb1d4ed6ff684d)

# Conflicts:
#	src/platform/packages/shared/kbn-scout/src/playwright/page_objects/discover_app.ts
#	x-pack/platform/plugins/shared/streams_app/test/scout/ui/tests/data_management/data_processing/outdated_documents.spec.ts
#	x-pack/platform/plugins/shared/streams_app/test/scout/ui/tests/discover_integration_classic.spec.ts
#	x-pack/platform/plugins/shared/streams_app/test/scout/ui/tests/discover_integration_wired.spec.ts