[Security Solution][Detection Engine] fixes docs version reference in actions test (#225611)
## Summary

We had a few cases of backport tests failing because version in docs
link is hardcoded as `current` but can be previous version.

Examples:
https://github.com/elastic/kibana/pull/225582
https://github.com/elastic/kibana/pull/225584

Failed assertion:

> Error: expected 'This rule\'s API key is unable to access all indices
that match the ["host_alias"] pattern. To learn how to update and manage
API keys, refer to
https://www.elastic.co/guide/en/kibana/9.1/alerting-setup.html#alerting-authorization.\n\nThis
rule is attempting to query data from Elasticsearch indices listed in
the "Index patterns" section of the rule definition, however no index
matching: ["host_alias"] was found. This warning will continue to appear
until a matching index is created or this rule is disabled.' to contain
'This rule\'s API key is unable to access all indices that match the
["host_alias"] pattern. To learn how to update and manage API keys,
refer to
https://www.elastic.co/guide/en/kibana/current/alerting-setup.html#alerting-authorization.'

(cherry picked from commit fefaea74fa838c8eecdc24f6588f68e2fc25eebe)