[8.7] [scalability testing] skip unloading archives after journey (#151476) (#151847)
# Backport

This will backport the following commits from `main` to `8.7`:
- [[scalability testing] skip unloading archives after journey
(#151476)](https://github.com/elastic/kibana/pull/151476)

<!--- Backport version: 8.9.7 -->

### Questions ?
Please refer to the [Backport tool
documentation](https://github.com/sqren/backport)

<!--BACKPORT [{"author":{"name":"Dzmitry
Lemechko","email":"dzmitry.lemechko@elastic.co"},"sourceCommit":{"committedDate":"2023-02-22T11:25:48Z","message":"[scalability
testing] skip unloading archives after journey (#151476)\n\n##
Summary\r\n\r\nSometimes scalability testing might make Kibana not
responding and it\r\ncauses after hook with unloading kbn archives
to\r\n[fail](https://buildkite.com/elastic/kibana-apis-capacity-testing/builds/241#01865418-2579-4559-bd4e-432c48a2104d):\r\n\r\n```\r\n2023-02-15T08:33:37.825Z
proc [scalability-tests] proc [gatling: test] Simulation
org.kibanaLoadTest.simulation.generic.GenericJourney completed in 268
seconds\r\n2023-02-15T08:38:06.749Z proc [scalability-tests] proc
[gatling: test]
java.lang.reflect.InvocationTargetException\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)\r\n2023-02-15T08:41:06.006Z proc [scalability-tests] proc
[gatling: test] \tat
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.plugin.util.ForkMain.runMain(ForkMain.java:67)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.plugin.util.ForkMain.main(ForkMain.java:35)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] Caused by:
java.lang.RuntimeException: Login request failed:
org.apache.http.NoHttpResponseException: localhost:5620 failed to
respond\r\n2023-02-15T08:41:06.006Z proc [scalability-tests] proc
[gatling: test] \tat
org.kibanaLoadTest.helpers.KbnClient.getCookie(KbnClient.scala:72)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.helpers.KbnClient.getClientAndConnectionManager(KbnClient.scala:50)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.helpers.KbnClient.unload(KbnClient.scala:139)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.$anonfun$new$5(GenericJourney.scala:153)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.$anonfun$new$5$adapted(GenericJourney.scala:153)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.$anonfun$testDataLoader$2(GenericJourney.scala:47)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.$anonfun$testDataLoader$2$adapted(GenericJourney.scala:46)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.testDataLoader(GenericJourney.scala:46)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.$anonfun$new$4(GenericJourney.scala:154)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.core.scenario.Simulation.$anonfun$params$18(Simulation.scala:176)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.core.scenario.Simulation.$anonfun$params$18$adapted(Simulation.scala:176)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
scala.collection.immutable.List.foreach(List.scala:333)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.core.scenario.Simulation.$anonfun$params$17(Simulation.scala:176)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.app.Runner.run(Runner.scala:62)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.app.Gatling$.start(Gatling.scala:89)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.app.Gatling$.fromArgs(Gatling.scala:51)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.app.Gatling$.main(Gatling.scala:39)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.app.Gatling.main(Gatling.scala)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \t... 6
more\r\n```\r\n\r\nThe journey is marked as failed though we actually
got the metrics. This\r\nPR add flag to Gatling runner command that
skips running cleanup on\r\njourney
teardown.","sha":"5c8bf9a94c2a46665e858a0a61dfdd078fa591fb","branchLabelMapping":{"^v8.8.0$":"main","^v(\\d+).(\\d+).\\d+$":"$1.$2"}},"sourcePullRequest":{"labels":["release_note:skip","wg:performance","v8.7.0","v8.8.0"],"number":151476,"url":"https://github.com/elastic/kibana/pull/151476","mergeCommit":{"message":"[scalability
testing] skip unloading archives after journey (#151476)\n\n##
Summary\r\n\r\nSometimes scalability testing might make Kibana not
responding and it\r\ncauses after hook with unloading kbn archives
to\r\n[fail](https://buildkite.com/elastic/kibana-apis-capacity-testing/builds/241#01865418-2579-4559-bd4e-432c48a2104d):\r\n\r\n```\r\n2023-02-15T08:33:37.825Z
proc [scalability-tests] proc [gatling: test] Simulation
org.kibanaLoadTest.simulation.generic.GenericJourney completed in 268
seconds\r\n2023-02-15T08:38:06.749Z proc [scalability-tests] proc
[gatling: test]
java.lang.reflect.InvocationTargetException\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)\r\n2023-02-15T08:41:06.006Z proc [scalability-tests] proc
[gatling: test] \tat
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.plugin.util.ForkMain.runMain(ForkMain.java:67)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.plugin.util.ForkMain.main(ForkMain.java:35)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] Caused by:
java.lang.RuntimeException: Login request failed:
org.apache.http.NoHttpResponseException: localhost:5620 failed to
respond\r\n2023-02-15T08:41:06.006Z proc [scalability-tests] proc
[gatling: test] \tat
org.kibanaLoadTest.helpers.KbnClient.getCookie(KbnClient.scala:72)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.helpers.KbnClient.getClientAndConnectionManager(KbnClient.scala:50)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.helpers.KbnClient.unload(KbnClient.scala:139)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.$anonfun$new$5(GenericJourney.scala:153)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.$anonfun$new$5$adapted(GenericJourney.scala:153)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.$anonfun$testDataLoader$2(GenericJourney.scala:47)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.$anonfun$testDataLoader$2$adapted(GenericJourney.scala:46)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.testDataLoader(GenericJourney.scala:46)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.$anonfun$new$4(GenericJourney.scala:154)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.core.scenario.Simulation.$anonfun$params$18(Simulation.scala:176)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.core.scenario.Simulation.$anonfun$params$18$adapted(Simulation.scala:176)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
scala.collection.immutable.List.foreach(List.scala:333)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.core.scenario.Simulation.$anonfun$params$17(Simulation.scala:176)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.app.Runner.run(Runner.scala:62)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.app.Gatling$.start(Gatling.scala:89)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.app.Gatling$.fromArgs(Gatling.scala:51)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.app.Gatling$.main(Gatling.scala:39)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.app.Gatling.main(Gatling.scala)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \t... 6
more\r\n```\r\n\r\nThe journey is marked as failed though we actually
got the metrics. This\r\nPR add flag to Gatling runner command that
skips running cleanup on\r\njourney
teardown.","sha":"5c8bf9a94c2a46665e858a0a61dfdd078fa591fb"}},"sourceBranch":"main","suggestedTargetBranches":["8.7"],"targetPullRequestStates":[{"branch":"8.7","label":"v8.7.0","labelRegex":"^v(\\d+).(\\d+).\\d+$","isSourceBranch":false,"state":"NOT_CREATED"},{"branch":"main","label":"v8.8.0","labelRegex":"^v8.8.0$","isSourceBranch":true,"state":"MERGED","url":"https://github.com/elastic/kibana/pull/151476","number":151476,"mergeCommit":{"message":"[scalability
testing] skip unloading archives after journey (#151476)\n\n##
Summary\r\n\r\nSometimes scalability testing might make Kibana not
responding and it\r\ncauses after hook with unloading kbn archives
to\r\n[fail](https://buildkite.com/elastic/kibana-apis-capacity-testing/builds/241#01865418-2579-4559-bd4e-432c48a2104d):\r\n\r\n```\r\n2023-02-15T08:33:37.825Z
proc [scalability-tests] proc [gatling: test] Simulation
org.kibanaLoadTest.simulation.generic.GenericJourney completed in 268
seconds\r\n2023-02-15T08:38:06.749Z proc [scalability-tests] proc
[gatling: test]
java.lang.reflect.InvocationTargetException\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)\r\n2023-02-15T08:41:06.006Z proc [scalability-tests] proc
[gatling: test] \tat
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.plugin.util.ForkMain.runMain(ForkMain.java:67)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.plugin.util.ForkMain.main(ForkMain.java:35)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] Caused by:
java.lang.RuntimeException: Login request failed:
org.apache.http.NoHttpResponseException: localhost:5620 failed to
respond\r\n2023-02-15T08:41:06.006Z proc [scalability-tests] proc
[gatling: test] \tat
org.kibanaLoadTest.helpers.KbnClient.getCookie(KbnClient.scala:72)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.helpers.KbnClient.getClientAndConnectionManager(KbnClient.scala:50)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.helpers.KbnClient.unload(KbnClient.scala:139)\r\n2023-02-15T08:41:06.006Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.$anonfun$new$5(GenericJourney.scala:153)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.$anonfun$new$5$adapted(GenericJourney.scala:153)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.$anonfun$testDataLoader$2(GenericJourney.scala:47)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.$anonfun$testDataLoader$2$adapted(GenericJourney.scala:46)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.testDataLoader(GenericJourney.scala:46)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
org.kibanaLoadTest.simulation.generic.GenericJourney.$anonfun$new$4(GenericJourney.scala:154)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.core.scenario.Simulation.$anonfun$params$18(Simulation.scala:176)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.core.scenario.Simulation.$anonfun$params$18$adapted(Simulation.scala:176)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
scala.collection.immutable.List.foreach(List.scala:333)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.core.scenario.Simulation.$anonfun$params$17(Simulation.scala:176)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.app.Runner.run(Runner.scala:62)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.app.Gatling$.start(Gatling.scala:89)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.app.Gatling$.fromArgs(Gatling.scala:51)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.app.Gatling$.main(Gatling.scala:39)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \tat
io.gatling.app.Gatling.main(Gatling.scala)\r\n2023-02-15T08:41:06.007Z
proc [scalability-tests] proc [gatling: test] \t... 6
more\r\n```\r\n\r\nThe journey is marked as failed though we actually
got the metrics. This\r\nPR add flag to Gatling runner command that
skips running cleanup on\r\njourney
teardown.","sha":"5c8bf9a94c2a46665e858a0a61dfdd078fa591fb"}}]}]
BACKPORT-->

Co-authored-by: Dzmitry Lemechko <dzmitry.lemechko@elastic.co>