[Serverless] Fix Console and Grok debugger functional tests (#172664)
Fixes https://github.com/elastic/kibana/issues/172632
Fixes https://github.com/elastic/kibana/issues/172668
Also fixes failing Grok debugger tests:
https://buildkite.com/elastic/kibana-flaky-test-suite-runner/builds/4199

## Summary

This PR fixes the serverless Console and Grok Debugger functional tests
by adding the correct serverless login and logout to the before/after
hooks. It seems that when they are missing, the tests fail with the
following error:

```
Error: retry.tryForTime timeout: Error: retry.try timeout: TimeoutError: Waiting for element to be located By(css selector, [data-test-subj="kibanaChrome"])
```

The PR also removes most of the Console test cases, since they are
already running in stateful. This will also resolve the flakiness that
is caused by one of these test cases.

Flaky test runner:
https://buildkite.com/elastic/kibana-flaky-test-suite-runner/builds/4215

(cherry picked from commit 8fb2e077cf8f933ddc404aadf7ba7e4f06511a24)