[Automatic Import] Fix Structured log template to use single quotes (#209736)
## Release Note

Fix Structured log template to use single quotes

### Summary

Currently with a single backslash as escape character the template is
setting up a double quote surrounding it and it causes YAML Exception
```
 1 |   - kv:
 2 |       field: message
 3 |       field_split: "\|"
--------------------------^

YAMLException: unknown escape sequence (3:22)
```

This PR fixes to use single quotes to not break YAML parsing.

(cherry picked from commit 8181858385efdc099b9ac517afe58ef6d1ba18a6)