[Security GenAI][Bug] OSS models do not work when streaming is ON (#12827) (#224129)
## Summary

Main ticket: https://github.com/elastic/security-team/issues/12827

These changes fix the issue with the locally running models over the
`HTTP` server. We do always use `HTTPS` agent even when URL uses HTTP
protocol. This leads to an error:

```
TypeError: Protocol "http:" not supported. Expected "https:"
    at new ClientRequest (node:_http_client:187:11)
    at request (node:http:101:10)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at AsyncLocalStorageRunContextManager.with (/kibana/node_modules/elastic-apm-node/lib/instrumentation/run-context/AsyncLocalStorageRunContextManager.js:57:36)
    at Instrumentation.withRunContext (/kibana/node_modules/elastic-apm-node/lib/instrumentation/index.js:1126:30)
    at wrappedHttpRequest (/kibana/node_modules/elastic-apm-node/lib/instrumentation/http-shared.js:292:21)
    at /kibana/node_modules/node-fetch/lib/index.js:1478:15
    at new Promise (<anonymous>)
    at fetch (/kibana/node_modules/node-fetch/lib/index.js:1447:9)
    at OpenAI.fetchWithTimeout (/kibana/node_modules/openai/src/core.ts:580:18)
    at OpenAI.makeRequest (/kibana/node_modules/openai/src/core.ts:476:33)
    at OpenAIConnector.invokeAsyncIterator (openai.ts:418:22)
    at Object.executor (executor.ts:99:18)
    at action_executor.ts:504:23
    at ActionExecutor.execute (action_executor.ts:153:12)
    at chat_openai.ts:162:28
    at RetryOperation._fn (/kibana/node_modules/p-retry/index.js:50:12)
```

### To test

Steps to reproduce the behavior:

1. Run locally hosted model and make sure that the chat completion url
uses the HTTP protocol
2. Add OSS model via Other (OpenAI Compatible Service) provider
3. Turn streaming ON
4. Try to chat via AI Assistant

Thanks @stephmilovic helping to solve the issue!

(cherry picked from commit 4c62313e1bb5a02beeb33e24ef6d5d9f758ab082)

# Conflicts:
#	x-pack/platform/plugins/shared/stack_connectors/server/connector_types/openai/openai.ts