[Discover] Switch from "at" to "charAt" for better browser support (#156474)
From the community forum: users can't access Discover on older browsers.

```
TypeError: t.at is not a function
at http://xxx:5601/61109/bundles/plugin/data/kibana/data.plugin.js:1:312992
at Array.forEach ()
at n (http://xxx:5601/61109/bundles/plugin/data/kibana/data.plugin.js:1:312956)
at s (http://xxx:5601/61109/bundles/plugin/discover/kibana/discover.chunk.0.js:1:10138)
at http://xxx:5601/61109/bundles/plugin/discover/kibana/discover.chunk.0.js:1:10215
at Array.map ()
at a (http://xxx:5601/61109/bundles/plugin/discover/kibana/discover.chunk.0.js:1:10207)
at http://xxx:5601/61109/bundles/plugin/discover/kibana/discover.chunk.0.js:1:8442
at http://xxx:5601/61109/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:334:27724
at t.s._next (http://xxx:5601/61109/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:6:33456)
```

- https://discuss.elastic.co/t/update-to-8-7-0/329525
-
https://discuss.elastic.co/t/elastic-8-7-0-error-in-discover-tab/332329/2

## Summary

This PR replaces `String` `.at` usage with `.charAt` so it does not
require a polyfill for older browsers.