[9.2] [Fleet] omit system properties when syncing ingest pipelines (#241096) (#241226)
# Backport

This will backport the following commits from `main` to `9.2`:
- [[Fleet] omit system properties when syncing ingest pipelines
(#241096)](https://github.com/elastic/kibana/pull/241096)

<!--- Backport version: 9.6.6 -->

### Questions ?
Please refer to the [Backport tool
documentation](https://github.com/sorenlouv/backport)

<!--BACKPORT [{"author":{"name":"Julia
Bardi","email":"90178898+juliaElastic@users.noreply.github.com"},"sourceCommit":{"committedDate":"2025-10-30T07:17:54Z","message":"[Fleet]
omit system properties when syncing ingest pipelines (#241096)\n\n##
Summary\n\nCloses
https://github.com/elastic/kibana/issues/230188\n\nOmit system
properties when creating ingest pipelines on
remote\nclusters.\nCurrently pipelines syncing fails with the
error\n```\n[2025-10-29T10:50:06.429+01:00][ERROR][plugins.fleet.fleet:sync-integrations-task:1.0.5]
Failed to install ingest_pipeline logs-system.auth@custom, error:
ResponseError: parse_exception\n Root causes:\n parse_exception:
Provided a pipeline property which is managed by the system:
created_date_millis.\n```\nIt seems the new fields were introduced by
elasticsearch in
9.2\nhttps://github.com/elastic/elasticsearch/pull/130847\n\nTo
verify:\n- Start 2 clusters and set up syncing between
them\nhttps://github.com/elastic/kibana/blob/main/x-pack/platform/plugins/shared/fleet/dev_docs/local_setup/remote_clusters_ccr.md\n-
Create a custom ingest pipeline e.g. `logs-system.auth@custom`\n- Wait
for sync to run\n- Verify that the sync is successful\n\n```\n# example
pipeline\n{\n description: 'description',\n processors: [ { set:
[Object] } ],\n version: 2,\n created_date_millis: 1761731006028,\n
modified_date_millis:
1761732134830\n}\n[2025-10-29T11:03:38.922+01:00][DEBUG][plugins.fleet.fleet:sync-integrations-task:1.0.5]
Updating ingest pipeline:
logs-system.auth@custom\n[2025-10-29T11:11:36.343+01:00][INFO
][plugins.fleet.fleet:sync-integrations-task:1.0.5]
[SyncIntegrationsTask] runTask ended: success\n```\n\n\n\n###
Checklist\n\nCheck the PR satisfies following conditions. \n\nReviewers
should verify this PR satisfies this list as well.\n\n- [ ] Any text
added follows [EUI's
writing\nguidelines](https://elastic.github.io/eui/#/guidelines/writing),
uses\nsentence case text and includes
[i18n\nsupport](https://github.com/elastic/kibana/blob/main/src/platform/packages/shared/kbn-i18n/README.md)\n-
[
]\n[Documentation](https://www.elastic.co/guide/en/kibana/master/development-documentation.html)\nwas
added for features that require explanation or tutorials\n- [ ] [Unit or
functional\ntests](https://www.elastic.co/guide/en/kibana/master/development-tests.html)\nwere
updated or added to match the most common scenarios\n- [ ] If a plugin
configuration key changed, check if it needs to be\nallowlisted in the
cloud and added to the
[docker\nlist](https://github.com/elastic/kibana/blob/main/src/dev/build/tasks/os_packages/docker_generator/resources/base/bin/kibana-docker)\n-
[ ] This was checked for breaking HTTP API changes, and any
breaking\nchanges have been approved by the breaking-change committee.
The\n`release_note:breaking` label should be applied in these
situations.\n- [ ] [Flaky
Test\nRunner](https://ci-stats.kibana.dev/trigger_flaky_test_runner/1)
was\nused on any tests changed\n- [ ] The PR description includes the
appropriate Release Notes section,\nand the correct `release_note:*`
label is applied per
the\n[guidelines](https://www.elastic.co/guide/en/kibana/master/contributing.html#kibana-release-notes-process)\n-
[ ] Review the
[backport\nguidelines](https://docs.google.com/document/d/1VyN5k91e5OVumlc0Gb9RPa3h1ewuPE705nRtioPiTvY/edit?usp=sharing)\nand
apply applicable `backport:*`
labels.","sha":"171e720d805c7f5215c46ed231de302f73560e0d","branchLabelMapping":{"^v9.3.0$":"main","^v(\\d+).(\\d+).\\d+$":"$1.$2"}},"sourcePullRequest":{"labels":["release_note:fix","Team:Fleet","backport:version","v9.3.0","v9.2.1"],"title":"[Fleet]
omit system properties when syncing ingest
pipelines","number":241096,"url":"https://github.com/elastic/kibana/pull/241096","mergeCommit":{"message":"[Fleet]
omit system properties when syncing ingest pipelines (#241096)\n\n##
Summary\n\nCloses
https://github.com/elastic/kibana/issues/230188\n\nOmit system
properties when creating ingest pipelines on
remote\nclusters.\nCurrently pipelines syncing fails with the
error\n```\n[2025-10-29T10:50:06.429+01:00][ERROR][plugins.fleet.fleet:sync-integrations-task:1.0.5]
Failed to install ingest_pipeline logs-system.auth@custom, error:
ResponseError: parse_exception\n Root causes:\n parse_exception:
Provided a pipeline property which is managed by the system:
created_date_millis.\n```\nIt seems the new fields were introduced by
elasticsearch in
9.2\nhttps://github.com/elastic/elasticsearch/pull/130847\n\nTo
verify:\n- Start 2 clusters and set up syncing between
them\nhttps://github.com/elastic/kibana/blob/main/x-pack/platform/plugins/shared/fleet/dev_docs/local_setup/remote_clusters_ccr.md\n-
Create a custom ingest pipeline e.g. `logs-system.auth@custom`\n- Wait
for sync to run\n- Verify that the sync is successful\n\n```\n# example
pipeline\n{\n description: 'description',\n processors: [ { set:
[Object] } ],\n version: 2,\n created_date_millis: 1761731006028,\n
modified_date_millis:
1761732134830\n}\n[2025-10-29T11:03:38.922+01:00][DEBUG][plugins.fleet.fleet:sync-integrations-task:1.0.5]
Updating ingest pipeline:
logs-system.auth@custom\n[2025-10-29T11:11:36.343+01:00][INFO
][plugins.fleet.fleet:sync-integrations-task:1.0.5]
[SyncIntegrationsTask] runTask ended: success\n```\n\n\n\n###
Checklist\n\nCheck the PR satisfies following conditions. \n\nReviewers
should verify this PR satisfies this list as well.\n\n- [ ] Any text
added follows [EUI's
writing\nguidelines](https://elastic.github.io/eui/#/guidelines/writing),
uses\nsentence case text and includes
[i18n\nsupport](https://github.com/elastic/kibana/blob/main/src/platform/packages/shared/kbn-i18n/README.md)\n-
[
]\n[Documentation](https://www.elastic.co/guide/en/kibana/master/development-documentation.html)\nwas
added for features that require explanation or tutorials\n- [ ] [Unit or
functional\ntests](https://www.elastic.co/guide/en/kibana/master/development-tests.html)\nwere
updated or added to match the most common scenarios\n- [ ] If a plugin
configuration key changed, check if it needs to be\nallowlisted in the
cloud and added to the
[docker\nlist](https://github.com/elastic/kibana/blob/main/src/dev/build/tasks/os_packages/docker_generator/resources/base/bin/kibana-docker)\n-
[ ] This was checked for breaking HTTP API changes, and any
breaking\nchanges have been approved by the breaking-change committee.
The\n`release_note:breaking` label should be applied in these
situations.\n- [ ] [Flaky
Test\nRunner](https://ci-stats.kibana.dev/trigger_flaky_test_runner/1)
was\nused on any tests changed\n- [ ] The PR description includes the
appropriate Release Notes section,\nand the correct `release_note:*`
label is applied per
the\n[guidelines](https://www.elastic.co/guide/en/kibana/master/contributing.html#kibana-release-notes-process)\n-
[ ] Review the
[backport\nguidelines](https://docs.google.com/document/d/1VyN5k91e5OVumlc0Gb9RPa3h1ewuPE705nRtioPiTvY/edit?usp=sharing)\nand
apply applicable `backport:*`
labels.","sha":"171e720d805c7f5215c46ed231de302f73560e0d"}},"sourceBranch":"main","suggestedTargetBranches":["9.2"],"targetPullRequestStates":[{"branch":"main","label":"v9.3.0","branchLabelMappingKey":"^v9.3.0$","isSourceBranch":true,"state":"MERGED","url":"https://github.com/elastic/kibana/pull/241096","number":241096,"mergeCommit":{"message":"[Fleet]
omit system properties when syncing ingest pipelines (#241096)\n\n##
Summary\n\nCloses
https://github.com/elastic/kibana/issues/230188\n\nOmit system
properties when creating ingest pipelines on
remote\nclusters.\nCurrently pipelines syncing fails with the
error\n```\n[2025-10-29T10:50:06.429+01:00][ERROR][plugins.fleet.fleet:sync-integrations-task:1.0.5]
Failed to install ingest_pipeline logs-system.auth@custom, error:
ResponseError: parse_exception\n Root causes:\n parse_exception:
Provided a pipeline property which is managed by the system:
created_date_millis.\n```\nIt seems the new fields were introduced by
elasticsearch in
9.2\nhttps://github.com/elastic/elasticsearch/pull/130847\n\nTo
verify:\n- Start 2 clusters and set up syncing between
them\nhttps://github.com/elastic/kibana/blob/main/x-pack/platform/plugins/shared/fleet/dev_docs/local_setup/remote_clusters_ccr.md\n-
Create a custom ingest pipeline e.g. `logs-system.auth@custom`\n- Wait
for sync to run\n- Verify that the sync is successful\n\n```\n# example
pipeline\n{\n description: 'description',\n processors: [ { set:
[Object] } ],\n version: 2,\n created_date_millis: 1761731006028,\n
modified_date_millis:
1761732134830\n}\n[2025-10-29T11:03:38.922+01:00][DEBUG][plugins.fleet.fleet:sync-integrations-task:1.0.5]
Updating ingest pipeline:
logs-system.auth@custom\n[2025-10-29T11:11:36.343+01:00][INFO
][plugins.fleet.fleet:sync-integrations-task:1.0.5]
[SyncIntegrationsTask] runTask ended: success\n```\n\n\n\n###
Checklist\n\nCheck the PR satisfies following conditions. \n\nReviewers
should verify this PR satisfies this list as well.\n\n- [ ] Any text
added follows [EUI's
writing\nguidelines](https://elastic.github.io/eui/#/guidelines/writing),
uses\nsentence case text and includes
[i18n\nsupport](https://github.com/elastic/kibana/blob/main/src/platform/packages/shared/kbn-i18n/README.md)\n-
[
]\n[Documentation](https://www.elastic.co/guide/en/kibana/master/development-documentation.html)\nwas
added for features that require explanation or tutorials\n- [ ] [Unit or
functional\ntests](https://www.elastic.co/guide/en/kibana/master/development-tests.html)\nwere
updated or added to match the most common scenarios\n- [ ] If a plugin
configuration key changed, check if it needs to be\nallowlisted in the
cloud and added to the
[docker\nlist](https://github.com/elastic/kibana/blob/main/src/dev/build/tasks/os_packages/docker_generator/resources/base/bin/kibana-docker)\n-
[ ] This was checked for breaking HTTP API changes, and any
breaking\nchanges have been approved by the breaking-change committee.
The\n`release_note:breaking` label should be applied in these
situations.\n- [ ] [Flaky
Test\nRunner](https://ci-stats.kibana.dev/trigger_flaky_test_runner/1)
was\nused on any tests changed\n- [ ] The PR description includes the
appropriate Release Notes section,\nand the correct `release_note:*`
label is applied per
the\n[guidelines](https://www.elastic.co/guide/en/kibana/master/contributing.html#kibana-release-notes-process)\n-
[ ] Review the
[backport\nguidelines](https://docs.google.com/document/d/1VyN5k91e5OVumlc0Gb9RPa3h1ewuPE705nRtioPiTvY/edit?usp=sharing)\nand
apply applicable `backport:*`
labels.","sha":"171e720d805c7f5215c46ed231de302f73560e0d"}},{"branch":"9.2","label":"v9.2.1","branchLabelMappingKey":"^v(\\d+).(\\d+).\\d+$","isSourceBranch":false,"state":"NOT_CREATED"}]}]
BACKPORT-->

Co-authored-by: Julia Bardi <90178898+juliaElastic@users.noreply.github.com>