[Fleet] return 403 if data stream query throws security exception (#225583)
## Summary

Closes https://github.com/elastic/kibana/issues/223107

Catch the `security_exception` from querying data streams and return a
403 error.
We already had the same in the `/data_streams` API:
https://github.com/elastic/kibana/blob/main/x-pack/platform/plugins/shared/fleet/server/services/epm/data_streams/get.ts#L26-L37

To verify:
- Create a role that has access to Fleet:All, Integrations:All and
DevTools:All
- Create a user that uses this role
- Log out and login with the new user
- Go to Dev Tools and call the installed packages API
- Expect 403 error

<img width="1502" alt="image"
src="https://github.com/user-attachments/assets/ef795381-ba12-4819-a099-0fa582375fde"
/>

```
GET kbn:/api/fleet/epm/packages/installed?showOnlyActiveDataStreams=true

{
  "statusCode": 403,
  "error": "Forbidden",
  "message": """Unauthorized to query fleet datastreams: security_exception
	Root causes:
		security_exception: action [indices:admin/data_stream/get] is unauthorized for user [fleet_all] with effective roles [fleet_all] on indices [synthetics-*-*,metrics-*-*,logs-*-*,traces-*-*,profiling-*], this action is granted by the index privileges [view_index_metadata,manage,all]"""
}
```

### Checklist

- [x] [Unit or functional
tests](https://www.elastic.co/guide/en/kibana/master/development-tests.html)
were updated or added to match the most common scenarios