[kbn-test] improve saml auth failure logging (#208216)
## Summary

sometimes we face failure during saml authentication and error message
is not very helpful:

```
Error: Failed to parse 'set-cookie' header
    at getCookieFromResponseHeaders (packages/kbn-test/src/auth/saml_auth.ts:61:11)
    at finishSAMLHandshake (packages/kbn-test/src/auth/saml_auth.ts:280:10)
    at createLocalSAMLSession (packages/kbn-test/src/auth/saml_auth.ts:333:18)
```

With this change we should know when it happened:

- we create SAML request by calling `/internal/security/login
- we finish SAML handshake by calling  `/api/security/saml/callback`

I also hope `response.data` to be useful for investigation

(cherry picked from commit 10505bd488f9ddd16fca5ce43784ed61b5b10e41)