[Alert details page] Fix exception in loading alert history stats (#208352)
## Summary

This PR fixes the following bug on the alert details page, not sure what
has changed to cause this issue:

```
Error: Unable to retrieve alert details for alert with id of "undefined" or with query "{"bool":{"must":[{"term":{"kibana.alert.rule.uuid":"f90968a7-8723-4bf6-9472-1053a4e70ec1"}},{"term":{"kibana.alert.instance.id":"host-2"}},{"range":{"kibana.alert.time_range":{"from":"now-30d","to":"now+1d"}}}]}}" and operation find
Error: ResponseError: x_content_parse_exception
        Caused by:
                x_content_parse_exception: [1:333] [bool] failed to parse field [must]
        Root causes:
                parsing_exception: [range] query does not support [from]
```

|Before|After|
|---|---|

|![image](https://github.com/user-attachments/assets/929e6f63-4d23-4e4b-9f3b-a878a543a53c)|![image](https://github.com/user-attachments/assets/5490f768-06df-4b69-9d14-e6b9be7dc6fa)|

(cherry picked from commit 95a160ca94e45ffd063f1037bce6eb1a5c5dd372)