[Obs AI Assistant] Return an empty object for tool arguments if empty (#207943)
## Summary

### Problem
While testing the EIS pre-configured connector via the Obs AI Assistant
LLM evaluation framework, noticed that all calls to the query tool fails
with the below error:
```
ChatCompletionError: Failed parsing arguments for query
          at Object.next (throw_serialized_chat_completion_errors.ts:29:17)
          at /Users/viduni/Workspace/Elastic/kibana/node_modules/rxjs/src/internal/operators/tap.ts:189:31
          ............................................................................................
          at processStream (stream_into_observable.ts:17:20)
          at processTicksAndRejections (node:internal/process/task_queues:95:5) {
        code: 'internalError',
        meta: {
          name: 'query',
          arguments: '',
          toolCalls: [
            {
              function: { name: 'query', arguments: '' },
              toolCallId: 'tooluse_ovVIDLH7SeWaxfnfjy8Q0w'
            }
          ]
        }
      }
```
This is because we are expecting arguments to be `'{}'` in here -
https://github.com/elastic/kibana/blob/main/x-pack/platform/plugins/shared/inference/server/util/validate_tool_calls.ts#L44

### Solution
If `arguments` are empty, set it as `{}` before validating the tool
calls.


### Checklist

- [ ] [Unit or functional
tests](https://www.elastic.co/guide/en/kibana/master/development-tests.html)
were updated or added to match the most common scenarios
- [x] The PR description includes the appropriate Release Notes section,
and the correct `release_note:*` label is applied per the
[guidelines](https://www.elastic.co/guide/en/kibana/master/contributing.html#kibana-release-notes-process)