[Security Solution] Disable MKI test for automatic migrations (#225426)
## Summary

There's an issue where the `esArchiverLoad` migrates SO if any index
starting with `.kibana` is affected.

```
CypressError: `cy.task('esArchiverLoad')` failed with the following error:

> security_exception
	Root causes:
		security_exception: action [indices:admin/settings/update] is unauthorized for user [testing-internal] with effective roles [superuser] on restricted indices [.kibana_security_solution_1,.kibana_alerting_cases_1,.kibana_task_manager_1,.kibana_usage_counters_1,.kibana_1,.kibana_ingest_1,.kibana_analytics_1], this action is granted by the index privileges [manage,all]

```

This PR disables the test for MKI so it doesn't interfere with the
release, we'll work on a fix in a separate PR

Example MKI execution

https://buildkite.com/elastic/kibana-serverless-security-solution-quality-gate-investigations/builds/2889

---------

Co-authored-by: Elastic Machine <elasticmachine@users.noreply.github.com>
(cherry picked from commit 7683dd912529fa5ee8ebf42226beb9ed679990d8)