[cli/keystore] Transpile sources in dev
Currently the keystore is not transpiling source files resulting in an
error when running from the scripts directory:
```
» node scripts/kibana_keystore.js
/home/jon/dev/kibana/src/cli_keystore/cli_keystore.js:9
import _ from 'lodash';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js
(internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require
(/home/jon/dev/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require
(/home/jon/dev/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require
(/home/jon/dev/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require
(/home/jon/dev/kibana/node_modules/require-in-the-middle/index.js:80:39)
```

This ensures source files are transpiled in development.