[Security Solution][Detection Engine] fixes warning toasts on exception flyout (#180800)
## Summary

 - addresses https://github.com/elastic/kibana/issues/160851

warning was displaying because of error

```JSON
{
  "name": "TypeError",
  "message": "indexPattern.getAllowHidden is not a function",
  "stack": "TypeError: indexPattern.getAllowHidden is not a function\n    at DataViewsServicePublic.getFieldsForIndexPattern (http://localhost:5601/kbn/XXXXXXXXXXXX/bundles/plugin/dataViews/1.0.0/dataViews.plugin.js:2519:131)\n    at http://localhost:5601/kbn/XXXXXXXXXXXX/bundles/plugin/securitySolution/1.0.0/securitySolution.chunk.63.js:200144:45\n    at fetchExtendedField (http://localhost:5601/kbn/XXXXXXXXXXXX/bundles/plugin/lists/1.0.0/lists.chunk.0.js:19767:38)\n    at BuilderEntryItem._entry$field3 (http://localhost:5601/kbn/XXXXXXXXXXXX/bundles/plugin/lists/1.0.0/lists.chunk.0.js:19772:5)\n    at invokePassiveEffectCreate (http://localhost:5601/kbn/XXXXXXXXXXXX/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:375924:20)\n    at HTMLUnknownElement.callCallback (http://localhost:5601/kbn/XXXXXXXXXXXX/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:356387:14)\n    at Object.invokeGuardedCallbackDev (http://localhost:5601/kbn/XXXXXXXXXXXX/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:356436:16)\n    at invokeGuardedCallback (http://localhost:5601/kbn/XXXXXXXXXXXX/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:356498:31)\n    at flushPassiveEffectsImpl (http://localhost:5601/kbn/XXXXXXXXXXXX/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:376011:9)\n    at unstable_runWithPriority (http://localhost:5601/kbn/XXXXXXXXXXXX/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:437229:12)"
}
```

which originated in
https://github.com/elastic/kibana/blob/8.13/src/plugins/data_views/common/data_views/data_views.ts#L539

```ts

      allowHidden:
        (indexPattern as DataViewSpec).allowHidden || (indexPattern as DataView)?.getAllowHidden(),

```

In this case index.allowHidden is `false`, so `getAllowHidden()` is
called. Because `getAllowHidden` is undefined, it causes error above.

In my fix, I check if `allowHidden` is set and if not, only after this
`getAllowHidden()` is getting called

(cherry picked from commit cefdb33a671a940103600adaaef4fa7c3afaf3af)