[ci] skip flaky cypress (#209104)
## Summary
Skipping this to unblock main builds.

Error: https://github.com/elastic/kibana/issues/209063
Thread: https://elastic.slack.com/archives/C01CM17B483/p1738315311849799
(cherry picked from commit f19636ea2a0efe54630b305c7c34bfa3ed96d549)