[Fleet] Fix flaky package policy integration test (#151769)
## Summary
Closes #151661
I think creating all of the package policies at once in this test is
causing it to be flaky, reverting to creating them one by one.

```
TypeError: Cannot read properties of undefined (reading 'id')
    at createPackagePolicy (upgrade.ts:1303:60)
```