[Entity Analytics] Fix leads generation not persisting in serveless (#288499)
## Summary

Fixes https://github.com/elastic/kibana/issues/288351

On Serverless, Threat Hunting Leads always showed "No entities, risk
scores, or alerts were found in the Entity Store" even when the Entity
Store was populated. Lead generation was actually running correctly and
computing valid leads, but every attempt to persist was failing, because
the index creating was throwing an error:

`[LeadGeneration] Failed to persist leads to
\".entity_analytics.entity-leads.entity-default\": Error: Failed to
create index: .entity_analytics.entity-leads.entity-default:
illegal_argument_exception: Settings [index.auto_expand_replicas] are
not available when running in serverless mode`

`auto_expand_replicas` was added to this index's settings in
https://github.com/elastic/kibana/pull/284625 however Serverless rejects
that setting.

### The fix

In the shared `createOrUpdateIndex` EA utility:
- `auto_expand_replicas` is no longer sent as part of `indices.create()`
call. It's applied afterward as a separate using `indices.putSettings()`
so that if it fails it doesn't affect the index creation.

Note: one other option was to check if we are on serverless and only
apply that setting if not, but that would involve a lot of prop drilling
to get `isServerless`.

## How to test

1. Start a local Serverless ES with EIS enabled and then Kibana
2. Enable Entity Analytics and populate the Entity Store with some data
3. Trigger Threat Hunting Leads generation
4. Leads should be created and visible from the EA homepage

Co-authored-by: Elastic Machine <elasticmachine@users.noreply.github.com>
(cherry picked from commit c1d408ec29651d44c81645f55435f0748ad66d04)