[Response Ops][Alerting] Switch to `logger.warn` for `no_shard_available_action_exception` encountered when collecting telemetry (#205520)
Resolves https://github.com/elastic/response-ops-team/issues/221

## Summary

Looking through the logs for this, the majority of these errors have the
following stack trace (14,000+ in the last 7 days):

```
ResponseError: search_phase_execution_exception
	Root causes:
		no_shard_available_action_exception: [es-es-search-686bf6b747-xldl8][100.65.77.183:9300][indices:data/read/search[phase/query]]
		no_shard_available_action_exception: null
    at KibanaTransport._request (/usr/share/kibana/node_modules/@elastic/transport/lib/Transport.js:543:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /usr/share/kibana/node_modules/@elastic/transport/lib/Transport.js:641:32
    at KibanaTransport.request (/usr/share/kibana/node_modules/@elastic/transport/lib/Transport.js:637:20)
    at KibanaTransport.request (/usr/share/kibana/node_modules/@kbn/core-elasticsearch-client-server-internal/src/create_transport.js:60:16)
    at ClientTraced.SearchApi [as search] (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/api/api/search.js:72:12)
    at getTotalAlertsCountAggregations (/usr/share/kibana/node_modules/@kbn/alerting-plugin/server/usage/lib/get_telemetry_from_alerts.js:42:21)
    at async Promise.all (index 6)
    at TaskManagerRunner.run (/usr/share/kibana/node_modules/@kbn/task-manager-plugin/server/task_running/task_runner.js:325:22)
```

Looking through the code, we are already catching these errors and
returning a default response for that telemetry object. The
`no_shard_available_action_exception` is not an issue with Kibana, it's
an ES issue, so this PR catches these types of errors and log them at a
debug level instead of a warn level to avoid polluting the logs with
errors we have no control over.

Excluding those results, we see a different and less frequent stack
trace (100+ in the last 15 days):

```
TypeError: Cannot read properties of undefined (reading 'by_rule_type_id')
    at getTotalAlertsCountAggregations (/usr/share/kibana/node_modules/@kbn/alerting-plugin/server/usage/lib/get_telemetry_from_alerts.js:49:109)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 6)
    at TaskManagerRunner.run (/usr/share/kibana/node_modules/@kbn/task-manager-plugin/server/task_running/task_runner.js:325:22)
```

For actions telemetry, the volume of these errors is much lower.
Unfortunately, we are not logging the stack trace for these errors so
it's harder to track down the source. I've updated the code to store the
stack trace as well as adding the same handling for
`no_shard_available_action_exception` under the assumption that it could
also be getting these errors.

---------

Co-authored-by: Elastic Machine <elasticmachine@users.noreply.github.com>
(cherry picked from commit 4e0c0a785ad8d8d6df66406542acda1189e2b817)