Improve maximum shards error detection (#238398)
## Summary
Addresses build failures such as
https://buildkite.com/elastic/kibana-elasticsearch-serverless-verify-and-promote/builds/4419/steps/canvas?jid=0199c911-61a6-45da-8dde-5051d866945f

```
illegal_argument_exception: Validation Failed: 1: this action would add [3] shards, but this cluster currently has [56]/[1] maximum index shards open; for more information, see https://www.elastic.co/docs/deploy-manage/production-guidance/optimize-performance/size-shards?version=current#troubleshooting-max-shards-open;]
```

The PR improves the detection to support different error strings
```
# before
but this cluster currently has [56]/[1] maximum normal shards open

# after
but this cluster currently has [56]/[1] maximum .* shards open
```

(cherry picked from commit 9a7c4570a522c815cd9a3f9b53b1c129aedf009e)