Update types, schemas, and saved objects for datasources.
Based on specs/examples at https://github.com/elastic/beats/blob/feature-ingest/x-pack/agent/docs/agent_configuration_example.yml#L28-L61 & https://github.com/elastic/beats/blob/c46ae67648b08f8d263de3eb7db870f77bbc2558/x-pack/agent/pkg/agent/program/testdata/single_config.yml#L22-L40

Create & list for /datasources API worked as expected

Fails type checks because of issues on one UI view (datasources table):
```
ERROR x-pack failed
      x-pack/plugins/ingest_manager/public/applications/ingest_manager/sections/agent_config/details_page/components/datasources_table.tsx:46:37 - error TS2339: Property 'name' does not exist on type 'DatasourceWithConfig'.

      46     originalDatasources?.map(({ id, name, inputs, package: datasourcePackage, configs }) => ({
                                             ~~~~

      x-pack/plugins/ingest_manager/public/applications/ingest_manager/sections/agent_config/details_page/components/datasources_table.tsx:51:40 - error TS2339: Property 'title' does not exist on type '{ name: string; version: string; }'.

      51       packageTitle: datasourcePackage?.title,
                                                ~~~~~

      x-pack/plugins/ingest_manager/public/applications/ingest_manager/sections/agent_config/details_page/components/datasources_table.tsx:53:46 - error TS2339: Property 'description' does not exist on type '{ name: string; version: string; }'.

      53       packageDescription: datasourcePackage?.description,
                                                      ~~~~~~~~~~~

      Found 3 errors.
```