[Ops] Add debug to manifest downloads @ trigger.sh (#179516)
## Summary
There's a step in `.buildkite/scripts/steps/artifacts/trigger.sh` that
fails with no traces or any hints what's wrong.

This PR adds a mechanism to print some info about the failure for the
happiness of the developer.

See: https://buildkite.com/elastic/kibana-artifacts-trigger/builds/9400
Instead of the above failure, it will fail like this:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   291  100   291    0     0   1443      0 --:--:-- --:--:-- --:--:--  1440
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   127  100   127    0     0    790      0 --:--:-- --:--:-- --:--:--   793
Error: https://artifacts-snapshot.elastic.co/kibana/latest/8.13.1-SNAPSHOT.json is not valid json
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>
jq: parse error: Invalid numeric literal at line 1, column 6
```