[8.8] [Discover] Switch from "at" to "charAt" for better browser support (#156474) (#156657)
# Backport

This will backport the following commits from `main` to `8.8`:
- [[Discover] Switch from "at" to "charAt" for better browser support
(#156474)](https://github.com/elastic/kibana/pull/156474)

<!--- Backport version: 8.9.7 -->

### Questions ?
Please refer to the [Backport tool
documentation](https://github.com/sqren/backport)

<!--BACKPORT [{"author":{"name":"Julia
Rechkunova","email":"julia.rechkunova@elastic.co"},"sourceCommit":{"committedDate":"2023-05-04T09:11:18Z","message":"[Discover]
Switch from \"at\" to \"charAt\" for better browser support
(#156474)\n\nFrom the community forum: users can't access Discover on
older browsers.\r\n\r\n```\r\nTypeError: t.at is not a function\r\nat
http://xxx:5601/61109/bundles/plugin/data/kibana/data.plugin.js:1:312992\r\nat
Array.forEach ()\r\nat n
(http://xxx:5601/61109/bundles/plugin/data/kibana/data.plugin.js:1:312956)\r\nat
s
(http://xxx:5601/61109/bundles/plugin/discover/kibana/discover.chunk.0.js:1:10138)\r\nat
http://xxx:5601/61109/bundles/plugin/discover/kibana/discover.chunk.0.js:1:10215\r\nat
Array.map ()\r\nat a
(http://xxx:5601/61109/bundles/plugin/discover/kibana/discover.chunk.0.js:1:10207)\r\nat
http://xxx:5601/61109/bundles/plugin/discover/kibana/discover.chunk.0.js:1:8442\r\nat
http://xxx:5601/61109/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:334:27724\r\nat
t.s._next
(http://xxx:5601/61109/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:6:33456)\r\n```\r\n\r\n-
https://discuss.elastic.co/t/update-to-8-7-0/329525\r\n-\r\nhttps://discuss.elastic.co/t/elastic-8-7-0-error-in-discover-tab/332329/2\r\n\r\n##
Summary\r\n\r\nThis PR replaces `String` `.at` usage with `.charAt` so
it does not\r\nrequire a polyfill for older
browsers.","sha":"396a2b63d461102cb312168adf9303265919c16c","branchLabelMapping":{"^v8.9.0$":"main","^v(\\d+).(\\d+).\\d+$":"$1.$2"}},"sourcePullRequest":{"labels":["Feature:Discover","release_note:fix","Team:DataDiscovery","v8.7.0","v8.8.0","v8.9.0"],"number":156474,"url":"https://github.com/elastic/kibana/pull/156474","mergeCommit":{"message":"[Discover]
Switch from \"at\" to \"charAt\" for better browser support
(#156474)\n\nFrom the community forum: users can't access Discover on
older browsers.\r\n\r\n```\r\nTypeError: t.at is not a function\r\nat
http://xxx:5601/61109/bundles/plugin/data/kibana/data.plugin.js:1:312992\r\nat
Array.forEach ()\r\nat n
(http://xxx:5601/61109/bundles/plugin/data/kibana/data.plugin.js:1:312956)\r\nat
s
(http://xxx:5601/61109/bundles/plugin/discover/kibana/discover.chunk.0.js:1:10138)\r\nat
http://xxx:5601/61109/bundles/plugin/discover/kibana/discover.chunk.0.js:1:10215\r\nat
Array.map ()\r\nat a
(http://xxx:5601/61109/bundles/plugin/discover/kibana/discover.chunk.0.js:1:10207)\r\nat
http://xxx:5601/61109/bundles/plugin/discover/kibana/discover.chunk.0.js:1:8442\r\nat
http://xxx:5601/61109/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:334:27724\r\nat
t.s._next
(http://xxx:5601/61109/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:6:33456)\r\n```\r\n\r\n-
https://discuss.elastic.co/t/update-to-8-7-0/329525\r\n-\r\nhttps://discuss.elastic.co/t/elastic-8-7-0-error-in-discover-tab/332329/2\r\n\r\n##
Summary\r\n\r\nThis PR replaces `String` `.at` usage with `.charAt` so
it does not\r\nrequire a polyfill for older
browsers.","sha":"396a2b63d461102cb312168adf9303265919c16c"}},"sourceBranch":"main","suggestedTargetBranches":["8.7","8.8"],"targetPullRequestStates":[{"branch":"8.7","label":"v8.7.0","labelRegex":"^v(\\d+).(\\d+).\\d+$","isSourceBranch":false,"state":"NOT_CREATED"},{"branch":"8.8","label":"v8.8.0","labelRegex":"^v(\\d+).(\\d+).\\d+$","isSourceBranch":false,"state":"NOT_CREATED"},{"branch":"main","label":"v8.9.0","labelRegex":"^v8.9.0$","isSourceBranch":true,"state":"MERGED","url":"https://github.com/elastic/kibana/pull/156474","number":156474,"mergeCommit":{"message":"[Discover]
Switch from \"at\" to \"charAt\" for better browser support
(#156474)\n\nFrom the community forum: users can't access Discover on
older browsers.\r\n\r\n```\r\nTypeError: t.at is not a function\r\nat
http://xxx:5601/61109/bundles/plugin/data/kibana/data.plugin.js:1:312992\r\nat
Array.forEach ()\r\nat n
(http://xxx:5601/61109/bundles/plugin/data/kibana/data.plugin.js:1:312956)\r\nat
s
(http://xxx:5601/61109/bundles/plugin/discover/kibana/discover.chunk.0.js:1:10138)\r\nat
http://xxx:5601/61109/bundles/plugin/discover/kibana/discover.chunk.0.js:1:10215\r\nat
Array.map ()\r\nat a
(http://xxx:5601/61109/bundles/plugin/discover/kibana/discover.chunk.0.js:1:10207)\r\nat
http://xxx:5601/61109/bundles/plugin/discover/kibana/discover.chunk.0.js:1:8442\r\nat
http://xxx:5601/61109/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:334:27724\r\nat
t.s._next
(http://xxx:5601/61109/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:6:33456)\r\n```\r\n\r\n-
https://discuss.elastic.co/t/update-to-8-7-0/329525\r\n-\r\nhttps://discuss.elastic.co/t/elastic-8-7-0-error-in-discover-tab/332329/2\r\n\r\n##
Summary\r\n\r\nThis PR replaces `String` `.at` usage with `.charAt` so
it does not\r\nrequire a polyfill for older
browsers.","sha":"396a2b63d461102cb312168adf9303265919c16c"}}]}]
BACKPORT-->

Co-authored-by: Julia Rechkunova <julia.rechkunova@elastic.co>