Add TS type for package-spec.
Clarify EPR types relationship with package spec. i.e. what required properties it makes optional, what properties it adds, which property types it changes, etc.

3 TS errors and I think they're all expected to be fixed by https://github.com/elastic/kibana/pull/84944

ERROR x-pack failed
      x-pack/plugins/fleet/public/applications/fleet/hooks/use_package_icon_type.ts:45:66 - error TS2339: Property 'path' does not exist on type 'PackageSpecIcon'.

      45     const localIconSrc = Array.isArray(svgIcons) && (svgIcons[0].path || svgIcons[0].src);
                                                                          ~~~~

      x-pack/plugins/fleet/public/applications/fleet/sections/epm/screens/detail/overview_panel.tsx:13:24 - error TS2339: Property 'readme' does not exist on type 'PackageInfo'.

      13   const { screenshots, readme, name, version } = props;
                                ~~~~~~

      x-pack/plugins/fleet/public/applications/fleet/sections/epm/screens/detail/overview_panel.tsx:18:36 - error TS2322: Type 'PackageSpecScreenshot[] | (PackageSpecScreenshot[] & RegistryImage[])' is not assignable to type 'RegistryImage[]'.
        Type 'PackageSpecScreenshot[]' is not assignable to type 'RegistryImage[]'.
          Property 'path' is missing in type 'PackageSpecScreenshot' but required in type 'RegistryImage'.

      18       {screenshots && <Screenshots images={screenshots} />}
                                            ~~~~~~

        x-pack/plugins/fleet/common/types/models/epm.ts:115:3
          115   path: string;
                ~~~~
          'path' is declared here.
        x-pack/plugins/fleet/public/applications/fleet/sections/epm/screens/detail/screenshots.tsx:14:3
          14   images: ScreenshotItem[];
               ~~~~~~
          The expected type comes from property 'images' which is declared here on type 'IntrinsicAttributes & ScreenshotProps'

      Found 3 errors.