Skip tests which require `read_failure_store` on ES 9.0
When tests run in Kibana 8.19 against ES 9.0 in a forward compatibility test runs, they raise the error:

```bash
illegal_argument_exception: unknown index privilege [read_failure_store]. a privilege must be either one of the predefined fixed indices privileges ...
```

This happens because the tests access endpoint which inquire user's index privileges including `read_failure_store`, which is not available in **ES 9.0** as `ES 9.0` does not support Failure Store.