[8.14] Fix Bedrock connector Security AI assistant auto title functionality (#184064) (#184780)
# Backport

This will backport the following commits from `main` to `8.14`:
- [Fix Bedrock connector Security AI assistant auto title functionality
(#184064)](https://github.com/elastic/kibana/pull/184064)

<!--- Backport version: 9.4.3 -->

### Questions ?
Please refer to the [Backport tool
documentation](https://github.com/sqren/backport)

<!--BACKPORT [{"author":{"name":"Patryk
Kopyciński","email":"contact@patrykkopycinski.com"},"sourceCommit":{"committedDate":"2024-06-04T19:45:03Z","message":"Fix
Bedrock connector Security AI assistant auto title functionality
(#184064)\n\n## Summary\r\n\r\nFixes an issue with auto title
functionality while using Bedrock\r\nconnector, the issue was in using
`assistant` role, which is not\r\nsupported as first
message\r\n```\r\n[2024-05-22T16:04:55.149+00:00][ERROR][plugins.actions.bedrock]
Error: Status code: 400. Message: API Error: Bad Request - messages:
first message must use the \"user\" role\r\n at BedrockConnector.request
(sub_action_connector.ts:198:15)\r\n at processTicksAndRejections
(node:internal/process/task_queues:95:5)\r\n at
BedrockConnector.runApiLatest (bedrock.ts:195:22)\r\n at
BedrockConnector.invokeAI (bedrock.ts:311:17)\r\n at Object.executor
(executor.ts:87:18)\r\n at action_executor.ts:492:23\r\n at
ActionExecutor.execute (action_executor.ts:147:12)\r\n at executeAction
(executor.ts:55:24)\r\n at Object.fn
(post_actions_connector_execute.ts:196:36)\r\n at
core_versioned_route.ts:189:22\r\n at Router.handle
(router.ts:267:30)\r\n at handler (router.ts:195:13)\r\n at
exports.Manager.execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\r\n
at Object.internals.handler
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/handler.js:46:20)\r\n
at exports.execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/handler.js:31:20)\r\n
at Request._lifecycle
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/request.js:371:32)\r\n
at Request._execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/request.js:281:9)
{\"tags\":[\".bedrock\",\"bedrock\",\"action-run-failed\"],\"error\":{\"stack_trace\":\"Error:
Status code: 400. Message: API Error: Bad Request - messages: first
message must use the \\\"user\\\" role\\n at BedrockConnector.request
(sub_action_connector.ts:198:15)\\n at processTicksAndRejections
(node:internal/process/task_queues:95:5)\\n at
BedrockConnector.runApiLatest (bedrock.ts:195:22)\\n at
BedrockConnector.invokeAI (bedrock.ts:311:17)\\n at Object.executor
(executor.ts:87:18)\\n at action_executor.ts:492:23\\n at
ActionExecutor.execute (action_executor.ts:147:12)\\n at executeAction
(executor.ts:55:24)\\n at Object.fn
(post_actions_connector_execute.ts:196:36)\\n at
core_versioned_route.ts:189:22\\n at Router.handle (router.ts:267:30)\\n
at handler (router.ts:195:13)\\n at exports.Manager.execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\\n
at Object.internals.handler
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/handler.js:46:20)\\n
at exports.execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/handler.js:31:20)\\n
at Request._lifecycle
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/request.js:371:32)\\n
at Request._execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/request.js:281:9)\"},\"service\":{\"node\":{\"roles\":[\"background_tasks\",\"ui\"]}}}\r\n```","sha":"5315fb177a1535d601b04e1486207ad4498131d3","branchLabelMapping":{"^v8.15.0$":"main","^v(\\d+).(\\d+).\\d+$":"$1.$2"}},"sourcePullRequest":{"labels":["release_note:skip","ci:cloud-deploy","v8.14.0","v8.15.0"],"title":"Fix
Bedrock connector Security AI assistant auto title
functionality","number":184064,"url":"https://github.com/elastic/kibana/pull/184064","mergeCommit":{"message":"Fix
Bedrock connector Security AI assistant auto title functionality
(#184064)\n\n## Summary\r\n\r\nFixes an issue with auto title
functionality while using Bedrock\r\nconnector, the issue was in using
`assistant` role, which is not\r\nsupported as first
message\r\n```\r\n[2024-05-22T16:04:55.149+00:00][ERROR][plugins.actions.bedrock]
Error: Status code: 400. Message: API Error: Bad Request - messages:
first message must use the \"user\" role\r\n at BedrockConnector.request
(sub_action_connector.ts:198:15)\r\n at processTicksAndRejections
(node:internal/process/task_queues:95:5)\r\n at
BedrockConnector.runApiLatest (bedrock.ts:195:22)\r\n at
BedrockConnector.invokeAI (bedrock.ts:311:17)\r\n at Object.executor
(executor.ts:87:18)\r\n at action_executor.ts:492:23\r\n at
ActionExecutor.execute (action_executor.ts:147:12)\r\n at executeAction
(executor.ts:55:24)\r\n at Object.fn
(post_actions_connector_execute.ts:196:36)\r\n at
core_versioned_route.ts:189:22\r\n at Router.handle
(router.ts:267:30)\r\n at handler (router.ts:195:13)\r\n at
exports.Manager.execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\r\n
at Object.internals.handler
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/handler.js:46:20)\r\n
at exports.execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/handler.js:31:20)\r\n
at Request._lifecycle
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/request.js:371:32)\r\n
at Request._execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/request.js:281:9)
{\"tags\":[\".bedrock\",\"bedrock\",\"action-run-failed\"],\"error\":{\"stack_trace\":\"Error:
Status code: 400. Message: API Error: Bad Request - messages: first
message must use the \\\"user\\\" role\\n at BedrockConnector.request
(sub_action_connector.ts:198:15)\\n at processTicksAndRejections
(node:internal/process/task_queues:95:5)\\n at
BedrockConnector.runApiLatest (bedrock.ts:195:22)\\n at
BedrockConnector.invokeAI (bedrock.ts:311:17)\\n at Object.executor
(executor.ts:87:18)\\n at action_executor.ts:492:23\\n at
ActionExecutor.execute (action_executor.ts:147:12)\\n at executeAction
(executor.ts:55:24)\\n at Object.fn
(post_actions_connector_execute.ts:196:36)\\n at
core_versioned_route.ts:189:22\\n at Router.handle (router.ts:267:30)\\n
at handler (router.ts:195:13)\\n at exports.Manager.execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\\n
at Object.internals.handler
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/handler.js:46:20)\\n
at exports.execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/handler.js:31:20)\\n
at Request._lifecycle
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/request.js:371:32)\\n
at Request._execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/request.js:281:9)\"},\"service\":{\"node\":{\"roles\":[\"background_tasks\",\"ui\"]}}}\r\n```","sha":"5315fb177a1535d601b04e1486207ad4498131d3"}},"sourceBranch":"main","suggestedTargetBranches":["8.14"],"targetPullRequestStates":[{"branch":"8.14","label":"v8.14.0","branchLabelMappingKey":"^v(\\d+).(\\d+).\\d+$","isSourceBranch":false,"state":"NOT_CREATED"},{"branch":"main","label":"v8.15.0","branchLabelMappingKey":"^v8.15.0$","isSourceBranch":true,"state":"MERGED","url":"https://github.com/elastic/kibana/pull/184064","number":184064,"mergeCommit":{"message":"Fix
Bedrock connector Security AI assistant auto title functionality
(#184064)\n\n## Summary\r\n\r\nFixes an issue with auto title
functionality while using Bedrock\r\nconnector, the issue was in using
`assistant` role, which is not\r\nsupported as first
message\r\n```\r\n[2024-05-22T16:04:55.149+00:00][ERROR][plugins.actions.bedrock]
Error: Status code: 400. Message: API Error: Bad Request - messages:
first message must use the \"user\" role\r\n at BedrockConnector.request
(sub_action_connector.ts:198:15)\r\n at processTicksAndRejections
(node:internal/process/task_queues:95:5)\r\n at
BedrockConnector.runApiLatest (bedrock.ts:195:22)\r\n at
BedrockConnector.invokeAI (bedrock.ts:311:17)\r\n at Object.executor
(executor.ts:87:18)\r\n at action_executor.ts:492:23\r\n at
ActionExecutor.execute (action_executor.ts:147:12)\r\n at executeAction
(executor.ts:55:24)\r\n at Object.fn
(post_actions_connector_execute.ts:196:36)\r\n at
core_versioned_route.ts:189:22\r\n at Router.handle
(router.ts:267:30)\r\n at handler (router.ts:195:13)\r\n at
exports.Manager.execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\r\n
at Object.internals.handler
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/handler.js:46:20)\r\n
at exports.execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/handler.js:31:20)\r\n
at Request._lifecycle
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/request.js:371:32)\r\n
at Request._execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/request.js:281:9)
{\"tags\":[\".bedrock\",\"bedrock\",\"action-run-failed\"],\"error\":{\"stack_trace\":\"Error:
Status code: 400. Message: API Error: Bad Request - messages: first
message must use the \\\"user\\\" role\\n at BedrockConnector.request
(sub_action_connector.ts:198:15)\\n at processTicksAndRejections
(node:internal/process/task_queues:95:5)\\n at
BedrockConnector.runApiLatest (bedrock.ts:195:22)\\n at
BedrockConnector.invokeAI (bedrock.ts:311:17)\\n at Object.executor
(executor.ts:87:18)\\n at action_executor.ts:492:23\\n at
ActionExecutor.execute (action_executor.ts:147:12)\\n at executeAction
(executor.ts:55:24)\\n at Object.fn
(post_actions_connector_execute.ts:196:36)\\n at
core_versioned_route.ts:189:22\\n at Router.handle (router.ts:267:30)\\n
at handler (router.ts:195:13)\\n at exports.Manager.execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\\n
at Object.internals.handler
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/handler.js:46:20)\\n
at exports.execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/handler.js:31:20)\\n
at Request._lifecycle
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/request.js:371:32)\\n
at Request._execute
(/Users/patrykkopycinski/Projects/kibana/node_modules/@hapi/hapi/lib/request.js:281:9)\"},\"service\":{\"node\":{\"roles\":[\"background_tasks\",\"ui\"]}}}\r\n```","sha":"5315fb177a1535d601b04e1486207ad4498131d3"}}]}]
BACKPORT-->

Co-authored-by: Patryk Kopyciński <contact@patrykkopycinski.com>