Skip flaky synthetics test
1)    Stateful Observability - Deployment-agnostic API integration tests
       SyntheticsAPITests
         getSyntheticsMonitors
           get many monitors
             without params:
       Error: {"statusCode":500,"error":"Internal Server Error","message":"Manifest file manifest.yml not found in paths."}
       + expected - actual
       -500
       +200
       at Assertion.assert (expect.js:100:11)
       at Assertion.eql (expect.js:244:8)
       at saveMonitor (get_monitor.ts:52:26)
       at processTicksAndRejections (node:internal/process/task_queues:95:5)
       at async Promise.all (index 3)
       at Context.<anonymous> (get_monitor.ts:85:30)
       at Object.apply (wrap_function.js:74:16)