[9.2] [CI] Improve limits.yml overage message (#241216) (#241234)
# Backport

This will backport the following commits from `main` to `9.2`:
- [[CI] Improve limits.yml overage message
(#241216)](https://github.com/elastic/kibana/pull/241216)

<!--- Backport version: 9.6.6 -->

### Questions ?
Please refer to the [Backport tool
documentation](https://github.com/sorenlouv/backport)

<!--BACKPORT [{"author":{"name":"Brad
White","email":"Ikuni17@users.noreply.github.com"},"sourceCommit":{"committedDate":"2025-10-30T08:09:08Z","message":"[CI]
Improve limits.yml overage message (#241216)\n\n## Summary\n\nThe
current error message is a bit confusing, so this PR improves it
and\nadds guidance to fix.\n### New Error\n```bash\nShip Kibana
Distribution Metrics to CI Stats\n succ shipped metrics from
target/optimizer_bundle_metrics.json\n succ shipped metrics from
build/kibana/node_modules/@kbn/ui-shared-deps-src/shared_built_assets/metrics.json\nERROR
Metric overages:\n page load bundle size for cloud plugin is greater
than the limit of 9676. The current value is 9684.\n To update the
limit, run the following command locally:\n node
scripts/build_kibana_platform_plugins --focus cloud --update-limits\n🚨
Error: The command exited with status 1\n```\n\n### Old
Error\n```bash\nShip Kibana Distribution Metrics to CI Stats\n succ
shipped metrics from target/optimizer_bundle_metrics.json\n succ shipped
metrics from
build/kibana/node_modules/@kbn/ui-shared-deps-src/shared_built_assets/metrics.json\nERROR
Metric overages:\n page load bundle size > cloud with value of 9684 is
greater than the limit of 9676\n🚨 Error: The command exited with status
1\n```","sha":"b44202bdfac4e0ce8324cb72d9feb82fab2da9d7","branchLabelMapping":{"^v9.3.0$":"main","^v(\\d+).(\\d+).\\d+$":"$1.$2"}},"sourcePullRequest":{"labels":["Team:Operations","release_note:skip","backport:all-open","v9.3.0"],"title":"[CI]
Improve limits.yml overage
message","number":241216,"url":"https://github.com/elastic/kibana/pull/241216","mergeCommit":{"message":"[CI]
Improve limits.yml overage message (#241216)\n\n## Summary\n\nThe
current error message is a bit confusing, so this PR improves it
and\nadds guidance to fix.\n### New Error\n```bash\nShip Kibana
Distribution Metrics to CI Stats\n succ shipped metrics from
target/optimizer_bundle_metrics.json\n succ shipped metrics from
build/kibana/node_modules/@kbn/ui-shared-deps-src/shared_built_assets/metrics.json\nERROR
Metric overages:\n page load bundle size for cloud plugin is greater
than the limit of 9676. The current value is 9684.\n To update the
limit, run the following command locally:\n node
scripts/build_kibana_platform_plugins --focus cloud --update-limits\n🚨
Error: The command exited with status 1\n```\n\n### Old
Error\n```bash\nShip Kibana Distribution Metrics to CI Stats\n succ
shipped metrics from target/optimizer_bundle_metrics.json\n succ shipped
metrics from
build/kibana/node_modules/@kbn/ui-shared-deps-src/shared_built_assets/metrics.json\nERROR
Metric overages:\n page load bundle size > cloud with value of 9684 is
greater than the limit of 9676\n🚨 Error: The command exited with status
1\n```","sha":"b44202bdfac4e0ce8324cb72d9feb82fab2da9d7"}},"sourceBranch":"main","suggestedTargetBranches":[],"targetPullRequestStates":[{"branch":"main","label":"v9.3.0","branchLabelMappingKey":"^v9.3.0$","isSourceBranch":true,"state":"MERGED","url":"https://github.com/elastic/kibana/pull/241216","number":241216,"mergeCommit":{"message":"[CI]
Improve limits.yml overage message (#241216)\n\n## Summary\n\nThe
current error message is a bit confusing, so this PR improves it
and\nadds guidance to fix.\n### New Error\n```bash\nShip Kibana
Distribution Metrics to CI Stats\n succ shipped metrics from
target/optimizer_bundle_metrics.json\n succ shipped metrics from
build/kibana/node_modules/@kbn/ui-shared-deps-src/shared_built_assets/metrics.json\nERROR
Metric overages:\n page load bundle size for cloud plugin is greater
than the limit of 9676. The current value is 9684.\n To update the
limit, run the following command locally:\n node
scripts/build_kibana_platform_plugins --focus cloud --update-limits\n🚨
Error: The command exited with status 1\n```\n\n### Old
Error\n```bash\nShip Kibana Distribution Metrics to CI Stats\n succ
shipped metrics from target/optimizer_bundle_metrics.json\n succ shipped
metrics from
build/kibana/node_modules/@kbn/ui-shared-deps-src/shared_built_assets/metrics.json\nERROR
Metric overages:\n page load bundle size > cloud with value of 9684 is
greater than the limit of 9676\n🚨 Error: The command exited with status
1\n```","sha":"b44202bdfac4e0ce8324cb72d9feb82fab2da9d7"}}]}]
BACKPORT-->

Co-authored-by: Brad White <Ikuni17@users.noreply.github.com>