[Rule details page] Fix Cannot read properties of undefined (reading 'statusCode') (#206023)
## Summary

Occasionally, we see the following error on the Observability rule
details page:

```
TypeError: Cannot read properties of undefined (reading 'statusCode')
```

This PR tries to fix this issue in order to capture the actual error and
avoid accessing `statusCode` when the error.body is undefined.

(cherry picked from commit 25e12a644501c9844ef3bbf4af8923ca30c0529e)